package com.wenjunhuang.codeepiphany.settings;

import com.intellij.openapi.fileChooser.FileChooserDescriptorFactory;
import com.intellij.openapi.options.ConfigurationException;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.ComponentValidator;
import com.intellij.openapi.ui.Splitter;
import com.intellij.openapi.ui.TextFieldWithBrowseButton;
import com.intellij.openapi.ui.ValidationInfo;
import com.intellij.openapi.util.text.StringUtil;
import com.intellij.ui.components.JBLabel;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.wenjunhuang.codeepiphany.PluginBundle;
import org.jetbrains.annotations.NotNull;
import scala.Option;

import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.ResourceBundle;

public class CodeEpiphanySettingsPanel extends SettingsUi<CodeEpiphanySettings.CodeEpiphanySettingsState> {
    private TextFieldWithBrowseButton myDatabaseFolder;
    private JPanel myRootPanel;

    public CodeEpiphanySettingsPanel(Project myProject) {
        super(myProject);
        $$$setupUI$$$();

        myDatabaseFolder.addBrowseFolderListener(PluginBundle.message("settings.databaseFolder.title"),
                null,
                myProject, FileChooserDescriptorFactory.createSingleFolderDescriptor());


        new ComponentValidator(this)
                .withOutlineProvider(ComponentValidator.CWBB_PROVIDER)
                .withValidator(() -> {
                    String text = myDatabaseFolder.getText();
                    if (StringUtil.isEmpty(text)) {
                        return new ValidationInfo(PluginBundle.message("settings.databaseFolder.error.empty"), myDatabaseFolder);
                    }
                    return null;
                }).installOn(myDatabaseFolder);
    }

    @Override
    public void reset(@NotNull CodeEpiphanySettings.CodeEpiphanySettingsState settings) {
        myDatabaseFolder.setText(settings.databaseFolder().getOrElse(() -> ""));
    }

    @Override
    public boolean isModified(CodeEpiphanySettings.CodeEpiphanySettingsState settings) {
        return !StringUtil.equals(settings.databaseFolder().getOrElse(() -> ""), myDatabaseFolder.getText());
    }

    @Override
    public void apply(CodeEpiphanySettings.CodeEpiphanySettingsState settings) throws ConfigurationException {
        var validationInfos = new ArrayList<ValidationInfo>();
        ComponentValidator.getInstance(myDatabaseFolder)
                .ifPresent(validator -> {
                    validator.revalidate();
                    var info = validator.getValidationInfo();
                    if (info != null) validationInfos.add(info);
                });
        if (validationInfos.isEmpty()) {
            settings.databaseFolder_$eq(Option.apply(myDatabaseFolder.getText()));
            myProject().getMessageBus().syncPublisher(CodeEpiphanySettings.DATABASE_FOLDER_TOPIC())
                    .databaseFolderChanged(new File(myDatabaseFolder.getText()));
        }

    }

    @NotNull
    @Override
    public JComponent getComponent() {
        return myRootPanel;
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        myRootPanel = new JPanel();
        myRootPanel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JBLabel jBLabel1 = new JBLabel();
        this.$$$loadLabelText$$$(jBLabel1, this.$$$getMessageFromBundle$$$("messages/PluginBundle", "settings.databaseFolder.label"));
        myRootPanel.add(jBLabel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        myRootPanel.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        myDatabaseFolder = new TextFieldWithBrowseButton();
        myRootPanel.add(myDatabaseFolder, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    private static Method $$$cachedGetBundleMethod$$$ = null;

    private String $$$getMessageFromBundle$$$(String path, String key) {
        ResourceBundle bundle;
        try {
            Class<?> thisClass = this.getClass();
            if ($$$cachedGetBundleMethod$$$ == null) {
                Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
                $$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
            }
            bundle = (ResourceBundle) $$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
        } catch (Exception e) {
            bundle = ResourceBundle.getBundle(path);
        }
        return bundle.getString(key);
    }

    /**
     * @noinspection ALL
     */
    private void $$$loadLabelText$$$(JLabel component, String text) {
        StringBuffer result = new StringBuffer();
        boolean haveMnemonic = false;
        char mnemonic = '\0';
        int mnemonicIndex = -1;
        for (int i = 0; i < text.length(); i++) {
            if (text.charAt(i) == '&') {
                i++;
                if (i == text.length()) break;
                if (!haveMnemonic && text.charAt(i) != '&') {
                    haveMnemonic = true;
                    mnemonic = text.charAt(i);
                    mnemonicIndex = result.length();
                }
            }
            result.append(text.charAt(i));
        }
        component.setText(result.toString());
        if (haveMnemonic) {
            component.setDisplayedMnemonic(mnemonic);
            component.setDisplayedMnemonicIndex(mnemonicIndex);
        }
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return myRootPanel;
    }

}
