package com.wenjunhuang.codeepiphany.utils.ui;

import com.intellij.ui.BrowserHyperlinkListener;
import com.intellij.ui.ScrollPaneFactory;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.intellij.util.ui.HTMLEditorKitBuilder;
import com.intellij.util.ui.JBUI;
import com.intellij.util.ui.components.BorderLayoutPanel;
import com.wenjunhuang.codeepiphany.PluginBundle;
import com.wenjunhuang.codeepiphany.model.CodeDojo;
import scala.Option;
import scala.Some;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class UnauthenticatedView extends BorderLayoutPanel {

    private JPanel myRoot;
    private JEditorPane myEditorPane;
    private SVGImagePanel myPluginIcon;

    public UnauthenticatedView(CodeDojo codeDojo) {
        this(codeDojo, Option.empty());
    }

    public UnauthenticatedView(CodeDojo codeDojo, Option<String> tips) {
        $$$setupUI$$$();
        myEditorPane.setEditorKit(HTMLEditorKitBuilder.simple());
        myEditorPane.addHyperlinkListener(new BrowserHyperlinkListener());
        if (tips instanceof Some<String> sometips) {
            myEditorPane.setText("<p align=\"center\">" + PluginBundle.message("unauthenticatedView.message", CodeDojo.show(codeDojo)) + "</p><br/><p>" + sometips.get() + "</p>");
        } else {
            myEditorPane.setText("<p align=\"center\">" + PluginBundle.message("unauthenticatedView.message", CodeDojo.show(codeDojo)) + "</p>");
        }

        myPluginIcon.image_$eq(codeDojo.getIconPath());
        setBorder(JBUI.Borders.empty());
        addToCenter(ScrollPaneFactory.createScrollPane(myRoot, true));
    }

    private void createUIComponents() {
        myPluginIcon = new SVGImagePanel();
    }

    public JComponent getComponent() {
        return myRoot;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        myRoot = new JPanel();
        myRoot.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        myRoot.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final Spacer spacer1 = new Spacer();
        myRoot.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        myRoot.add(spacer2, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        myEditorPane = new JEditorPane();
        myEditorPane.setContentType("text/html");
        myEditorPane.setEditable(false);
        myEditorPane.setOpaque(false);
        myEditorPane.setText("<html>\r\n  <head>\r\n    \r\n  </head>\r\n  <body>\r\n  </body>\r\n</html>\r\n");
        myRoot.add(myEditorPane, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, -1), null, 0, false));
        myRoot.add(myPluginIcon, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(64, 64), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return myRoot;
    }


}
