version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/webview"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "develop"
    assignees:
      - "WenjunHuang"
    commit-message:
      prefix: "chore(deps): "
      
  # Enable version updates for SBT
  - package-ecosystem: "sbt"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "develop"
    assignees:
      - "WenjunHuang"
    commit-message:
      prefix: "chore(deps): "
      
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: "develop"
    assignees:
      - "WenjunHuang"
    commit-message:
      prefix: "chore(deps): " 