version = 3.7.15
runner.dialect = scala3

maxColumn = 120
preset=default
indent.defnSite = 2
optIn.configStyleArguments = false

project.git = true
spaces.inImportCurlyBraces = true
includeCurlyBraceInSelectChains = false
rewrite.rules = [SortImports, RedundantParens, SortModifiers]
align.preset = more

