/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables;


import com.wenjunhuang.codeepiphany.database.DefaultSchema;
import com.wenjunhuang.codeepiphany.database.tables.records.AtcoderProblemsFtsRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AtcoderProblemsFts extends TableImpl<AtcoderProblemsFtsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>atcoder_problems_fts</code>
     */
    public static final AtcoderProblemsFts ATCODER_PROBLEMS_FTS = new AtcoderProblemsFts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AtcoderProblemsFtsRecord> getRecordType() {
        return AtcoderProblemsFtsRecord.class;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<AtcoderProblemsFtsRecord, Object> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<AtcoderProblemsFtsRecord, Object> PROBLEMID = createField(DSL.name("problemId"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<AtcoderProblemsFtsRecord, Object> CONTESTID = createField(DSL.name("contestId"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<AtcoderProblemsFtsRecord, Object> PROBLEMINDEX = createField(DSL.name("problemIndex"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<AtcoderProblemsFtsRecord, Object> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<AtcoderProblemsFtsRecord, Object> TITLE = createField(DSL.name("title"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<AtcoderProblemsFtsRecord, Object> SHORTESTSUBMISSIONID = createField(DSL.name("shortestSubmissionId"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<AtcoderProblemsFtsRecord, Object> SHORTESTCONTESTID = createField(DSL.name("shortestContestId"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<AtcoderProblemsFtsRecord, Object> SHORTESTUSERID = createField(DSL.name("shortestUserId"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<AtcoderProblemsFtsRecord, Object> FASTESTSUBMISSIONID = createField(DSL.name("fastestSubmissionId"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<AtcoderProblemsFtsRecord, Object> FASTESTCONTESTID = createField(DSL.name("fastestContestId"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<AtcoderProblemsFtsRecord, Object> FASTESTUSERID = createField(DSL.name("fastestUserId"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<AtcoderProblemsFtsRecord, Object> FIRSTSUBMISSIONID = createField(DSL.name("firstSubmissionId"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<AtcoderProblemsFtsRecord, Object> FIRSTCONTESTID = createField(DSL.name("firstContestId"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<AtcoderProblemsFtsRecord, Object> FIRSTUSERID = createField(DSL.name("firstUserId"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<AtcoderProblemsFtsRecord, Object> SOLVERCOUNT = createField(DSL.name("solverCount"), org.jooq.impl.SQLDataType.OTHER, this, "");

    private AtcoderProblemsFts(Name alias, Table<AtcoderProblemsFtsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AtcoderProblemsFts(Name alias, Table<AtcoderProblemsFtsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>atcoder_problems_fts</code> table reference
     */
    public AtcoderProblemsFts(String alias) {
        this(DSL.name(alias), ATCODER_PROBLEMS_FTS);
    }

    /**
     * Create an aliased <code>atcoder_problems_fts</code> table reference
     */
    public AtcoderProblemsFts(Name alias) {
        this(alias, ATCODER_PROBLEMS_FTS);
    }

    /**
     * Create a <code>atcoder_problems_fts</code> table reference
     */
    public AtcoderProblemsFts() {
        this(DSL.name("atcoder_problems_fts"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public AtcoderProblemsFts as(String alias) {
        return new AtcoderProblemsFts(DSL.name(alias), this);
    }

    @Override
    public AtcoderProblemsFts as(Name alias) {
        return new AtcoderProblemsFts(alias, this);
    }

    @Override
    public AtcoderProblemsFts as(Table<?> alias) {
        return new AtcoderProblemsFts(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AtcoderProblemsFts rename(String name) {
        return new AtcoderProblemsFts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AtcoderProblemsFts rename(Name name) {
        return new AtcoderProblemsFts(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AtcoderProblemsFts rename(Table<?> name) {
        return new AtcoderProblemsFts(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderProblemsFts where(Condition condition) {
        return new AtcoderProblemsFts(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderProblemsFts where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderProblemsFts where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderProblemsFts where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AtcoderProblemsFts where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AtcoderProblemsFts where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AtcoderProblemsFts where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AtcoderProblemsFts where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderProblemsFts whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderProblemsFts whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
