/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables;


import com.wenjunhuang.codeepiphany.database.DefaultSchema;
import com.wenjunhuang.codeepiphany.database.Keys;
import com.wenjunhuang.codeepiphany.database.tables.records.AtcoderProblemsRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AtcoderProblems extends TableImpl<AtcoderProblemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>atcoder_problems</code>
     */
    public static final AtcoderProblems ATCODER_PROBLEMS = new AtcoderProblems();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AtcoderProblemsRecord> getRecordType() {
        return AtcoderProblemsRecord.class;
    }

    /**
     * The column <code>atcoder_problems.problemId</code>.
     */
    public final TableField<AtcoderProblemsRecord, String> PROBLEMID = createField(DSL.name("problemId"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>atcoder_problems.contestId</code>.
     */
    public final TableField<AtcoderProblemsRecord, String> CONTESTID = createField(DSL.name("contestId"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>atcoder_problems.problemIndex</code>.
     */
    public final TableField<AtcoderProblemsRecord, String> PROBLEMINDEX = createField(DSL.name("problemIndex"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>atcoder_problems.name</code>.
     */
    public final TableField<AtcoderProblemsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>atcoder_problems.title</code>.
     */
    public final TableField<AtcoderProblemsRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>atcoder_problems.shortestSubmissionId</code>.
     */
    public final TableField<AtcoderProblemsRecord, Long> SHORTESTSUBMISSIONID = createField(DSL.name("shortestSubmissionId"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>atcoder_problems.shortestContestId</code>.
     */
    public final TableField<AtcoderProblemsRecord, String> SHORTESTCONTESTID = createField(DSL.name("shortestContestId"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>atcoder_problems.shortestUserId</code>.
     */
    public final TableField<AtcoderProblemsRecord, String> SHORTESTUSERID = createField(DSL.name("shortestUserId"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>atcoder_problems.fastestSubmissionId</code>.
     */
    public final TableField<AtcoderProblemsRecord, Long> FASTESTSUBMISSIONID = createField(DSL.name("fastestSubmissionId"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>atcoder_problems.fastestContestId</code>.
     */
    public final TableField<AtcoderProblemsRecord, String> FASTESTCONTESTID = createField(DSL.name("fastestContestId"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>atcoder_problems.fastestUserId</code>.
     */
    public final TableField<AtcoderProblemsRecord, String> FASTESTUSERID = createField(DSL.name("fastestUserId"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>atcoder_problems.firstSubmissionId</code>.
     */
    public final TableField<AtcoderProblemsRecord, Long> FIRSTSUBMISSIONID = createField(DSL.name("firstSubmissionId"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>atcoder_problems.firstContestId</code>.
     */
    public final TableField<AtcoderProblemsRecord, String> FIRSTCONTESTID = createField(DSL.name("firstContestId"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>atcoder_problems.firstUserId</code>.
     */
    public final TableField<AtcoderProblemsRecord, String> FIRSTUSERID = createField(DSL.name("firstUserId"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>atcoder_problems.solverCount</code>.
     */
    public final TableField<AtcoderProblemsRecord, Integer> SOLVERCOUNT = createField(DSL.name("solverCount"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>atcoder_problems.id</code>.
     */
    public final TableField<AtcoderProblemsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    private AtcoderProblems(Name alias, Table<AtcoderProblemsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AtcoderProblems(Name alias, Table<AtcoderProblemsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>atcoder_problems</code> table reference
     */
    public AtcoderProblems(String alias) {
        this(DSL.name(alias), ATCODER_PROBLEMS);
    }

    /**
     * Create an aliased <code>atcoder_problems</code> table reference
     */
    public AtcoderProblems(Name alias) {
        this(alias, ATCODER_PROBLEMS);
    }

    /**
     * Create a <code>atcoder_problems</code> table reference
     */
    public AtcoderProblems() {
        this(DSL.name("atcoder_problems"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<AtcoderProblemsRecord> getPrimaryKey() {
        return Keys.ATCODER_PROBLEMS__PK_ATCODER_PROBLEMS;
    }

    @Override
    public AtcoderProblems as(String alias) {
        return new AtcoderProblems(DSL.name(alias), this);
    }

    @Override
    public AtcoderProblems as(Name alias) {
        return new AtcoderProblems(alias, this);
    }

    @Override
    public AtcoderProblems as(Table<?> alias) {
        return new AtcoderProblems(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AtcoderProblems rename(String name) {
        return new AtcoderProblems(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AtcoderProblems rename(Name name) {
        return new AtcoderProblems(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AtcoderProblems rename(Table<?> name) {
        return new AtcoderProblems(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderProblems where(Condition condition) {
        return new AtcoderProblems(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderProblems where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderProblems where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderProblems where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AtcoderProblems where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AtcoderProblems where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AtcoderProblems where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AtcoderProblems where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderProblems whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderProblems whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
