/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables;


import com.wenjunhuang.codeepiphany.database.DefaultSchema;
import com.wenjunhuang.codeepiphany.database.Keys;
import com.wenjunhuang.codeepiphany.database.tables.records.AtcoderContestsRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AtcoderContests extends TableImpl<AtcoderContestsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>atcoder_contests</code>
     */
    public static final AtcoderContests ATCODER_CONTESTS = new AtcoderContests();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AtcoderContestsRecord> getRecordType() {
        return AtcoderContestsRecord.class;
    }

    /**
     * The column <code>atcoder_contests.contestId</code>.
     */
    public final TableField<AtcoderContestsRecord, String> CONTESTID = createField(DSL.name("contestId"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>atcoder_contests.startEpochSecond</code>.
     */
    public final TableField<AtcoderContestsRecord, Long> STARTEPOCHSECOND = createField(DSL.name("startEpochSecond"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>atcoder_contests.durationSecond</code>.
     */
    public final TableField<AtcoderContestsRecord, Long> DURATIONSECOND = createField(DSL.name("durationSecond"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>atcoder_contests.title</code>.
     */
    public final TableField<AtcoderContestsRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>atcoder_contests.rateChange</code>.
     */
    public final TableField<AtcoderContestsRecord, String> RATECHANGE = createField(DSL.name("rateChange"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>atcoder_contests.id</code>.
     */
    public final TableField<AtcoderContestsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    private AtcoderContests(Name alias, Table<AtcoderContestsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AtcoderContests(Name alias, Table<AtcoderContestsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>atcoder_contests</code> table reference
     */
    public AtcoderContests(String alias) {
        this(DSL.name(alias), ATCODER_CONTESTS);
    }

    /**
     * Create an aliased <code>atcoder_contests</code> table reference
     */
    public AtcoderContests(Name alias) {
        this(alias, ATCODER_CONTESTS);
    }

    /**
     * Create a <code>atcoder_contests</code> table reference
     */
    public AtcoderContests() {
        this(DSL.name("atcoder_contests"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<AtcoderContestsRecord> getPrimaryKey() {
        return Keys.ATCODER_CONTESTS__PK_ATCODER_CONTESTS;
    }

    @Override
    public AtcoderContests as(String alias) {
        return new AtcoderContests(DSL.name(alias), this);
    }

    @Override
    public AtcoderContests as(Name alias) {
        return new AtcoderContests(alias, this);
    }

    @Override
    public AtcoderContests as(Table<?> alias) {
        return new AtcoderContests(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AtcoderContests rename(String name) {
        return new AtcoderContests(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AtcoderContests rename(Name name) {
        return new AtcoderContests(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AtcoderContests rename(Table<?> name) {
        return new AtcoderContests(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderContests where(Condition condition) {
        return new AtcoderContests(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderContests where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderContests where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderContests where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AtcoderContests where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AtcoderContests where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AtcoderContests where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AtcoderContests where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderContests whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderContests whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
