/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables;


import com.wenjunhuang.codeepiphany.database.DefaultSchema;
import com.wenjunhuang.codeepiphany.database.Keys;
import com.wenjunhuang.codeepiphany.database.tables.Challenge.ChallengePath;
import com.wenjunhuang.codeepiphany.database.tables.records.AtcoderChallengeRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AtcoderChallenge extends TableImpl<AtcoderChallengeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>atcoder_challenge</code>
     */
    public static final AtcoderChallenge ATCODER_CHALLENGE = new AtcoderChallenge();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AtcoderChallengeRecord> getRecordType() {
        return AtcoderChallengeRecord.class;
    }

    /**
     * The column <code>atcoder_challenge.id</code>.
     */
    public final TableField<AtcoderChallengeRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>atcoder_challenge.difficulty</code>.
     */
    public final TableField<AtcoderChallengeRecord, Integer> DIFFICULTY = createField(DSL.name("difficulty"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>atcoder_challenge.contestId</code>.
     */
    public final TableField<AtcoderChallengeRecord, String> CONTESTID = createField(DSL.name("contestId"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>atcoder_challenge.problemIndex</code>.
     */
    public final TableField<AtcoderChallengeRecord, String> PROBLEMINDEX = createField(DSL.name("problemIndex"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>atcoder_challenge.title</code>.
     */
    public final TableField<AtcoderChallengeRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "");

    private AtcoderChallenge(Name alias, Table<AtcoderChallengeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AtcoderChallenge(Name alias, Table<AtcoderChallengeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>atcoder_challenge</code> table reference
     */
    public AtcoderChallenge(String alias) {
        this(DSL.name(alias), ATCODER_CHALLENGE);
    }

    /**
     * Create an aliased <code>atcoder_challenge</code> table reference
     */
    public AtcoderChallenge(Name alias) {
        this(alias, ATCODER_CHALLENGE);
    }

    /**
     * Create a <code>atcoder_challenge</code> table reference
     */
    public AtcoderChallenge() {
        this(DSL.name("atcoder_challenge"), null);
    }

    public <O extends Record> AtcoderChallenge(Table<O> path, ForeignKey<O, AtcoderChallengeRecord> childPath, InverseForeignKey<O, AtcoderChallengeRecord> parentPath) {
        super(path, childPath, parentPath, ATCODER_CHALLENGE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AtcoderChallengePath extends AtcoderChallenge implements Path<AtcoderChallengeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AtcoderChallengePath(Table<O> path, ForeignKey<O, AtcoderChallengeRecord> childPath, InverseForeignKey<O, AtcoderChallengeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AtcoderChallengePath(Name alias, Table<AtcoderChallengeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AtcoderChallengePath as(String alias) {
            return new AtcoderChallengePath(DSL.name(alias), this);
        }

        @Override
        public AtcoderChallengePath as(Name alias) {
            return new AtcoderChallengePath(alias, this);
        }

        @Override
        public AtcoderChallengePath as(Table<?> alias) {
            return new AtcoderChallengePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<AtcoderChallengeRecord> getPrimaryKey() {
        return Keys.ATCODER_CHALLENGE__PK_ATCODER_CHALLENGE;
    }

    @Override
    public List<ForeignKey<AtcoderChallengeRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ATCODER_CHALLENGE__FK_ATCODER_CHALLENGE_PK_CHALLENGE);
    }

    private transient ChallengePath _challenge;

    /**
     * Get the implicit join path to the <code>challenge</code> table.
     */
    public ChallengePath challenge() {
        if (_challenge == null)
            _challenge = new ChallengePath(this, Keys.ATCODER_CHALLENGE__FK_ATCODER_CHALLENGE_PK_CHALLENGE, null);

        return _challenge;
    }

    @Override
    public AtcoderChallenge as(String alias) {
        return new AtcoderChallenge(DSL.name(alias), this);
    }

    @Override
    public AtcoderChallenge as(Name alias) {
        return new AtcoderChallenge(alias, this);
    }

    @Override
    public AtcoderChallenge as(Table<?> alias) {
        return new AtcoderChallenge(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AtcoderChallenge rename(String name) {
        return new AtcoderChallenge(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AtcoderChallenge rename(Name name) {
        return new AtcoderChallenge(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AtcoderChallenge rename(Table<?> name) {
        return new AtcoderChallenge(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderChallenge where(Condition condition) {
        return new AtcoderChallenge(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderChallenge where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderChallenge where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderChallenge where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AtcoderChallenge where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AtcoderChallenge where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AtcoderChallenge where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AtcoderChallenge where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderChallenge whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderChallenge whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
