/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables;


import com.wenjunhuang.codeepiphany.database.DefaultSchema;
import com.wenjunhuang.codeepiphany.database.tables.records.AtcoderContestsFtsRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AtcoderContestsFts extends TableImpl<AtcoderContestsFtsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>atcoder_contests_fts</code>
     */
    public static final AtcoderContestsFts ATCODER_CONTESTS_FTS = new AtcoderContestsFts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AtcoderContestsFtsRecord> getRecordType() {
        return AtcoderContestsFtsRecord.class;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<AtcoderContestsFtsRecord, Object> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<AtcoderContestsFtsRecord, Object> CONTESTID = createField(DSL.name("contestId"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<AtcoderContestsFtsRecord, Object> STARTEPOCHSECOND = createField(DSL.name("startEpochSecond"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<AtcoderContestsFtsRecord, Object> DURATIONSECOND = createField(DSL.name("durationSecond"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<AtcoderContestsFtsRecord, Object> TITLE = createField(DSL.name("title"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<AtcoderContestsFtsRecord, Object> RATECHANGE = createField(DSL.name("rateChange"), org.jooq.impl.SQLDataType.OTHER, this, "");

    private AtcoderContestsFts(Name alias, Table<AtcoderContestsFtsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AtcoderContestsFts(Name alias, Table<AtcoderContestsFtsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>atcoder_contests_fts</code> table reference
     */
    public AtcoderContestsFts(String alias) {
        this(DSL.name(alias), ATCODER_CONTESTS_FTS);
    }

    /**
     * Create an aliased <code>atcoder_contests_fts</code> table reference
     */
    public AtcoderContestsFts(Name alias) {
        this(alias, ATCODER_CONTESTS_FTS);
    }

    /**
     * Create a <code>atcoder_contests_fts</code> table reference
     */
    public AtcoderContestsFts() {
        this(DSL.name("atcoder_contests_fts"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public AtcoderContestsFts as(String alias) {
        return new AtcoderContestsFts(DSL.name(alias), this);
    }

    @Override
    public AtcoderContestsFts as(Name alias) {
        return new AtcoderContestsFts(alias, this);
    }

    @Override
    public AtcoderContestsFts as(Table<?> alias) {
        return new AtcoderContestsFts(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AtcoderContestsFts rename(String name) {
        return new AtcoderContestsFts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AtcoderContestsFts rename(Name name) {
        return new AtcoderContestsFts(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AtcoderContestsFts rename(Table<?> name) {
        return new AtcoderContestsFts(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderContestsFts where(Condition condition) {
        return new AtcoderContestsFts(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderContestsFts where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderContestsFts where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderContestsFts where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AtcoderContestsFts where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AtcoderContestsFts where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AtcoderContestsFts where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AtcoderContestsFts where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderContestsFts whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AtcoderContestsFts whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
