/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables;


import com.wenjunhuang.codeepiphany.database.DefaultSchema;
import com.wenjunhuang.codeepiphany.database.Indexes;
import com.wenjunhuang.codeepiphany.database.Keys;
import com.wenjunhuang.codeepiphany.database.tables.Challenge.ChallengePath;
import com.wenjunhuang.codeepiphany.database.tables.HackerrankChallengeLanguage.HackerrankChallengeLanguagePath;
import com.wenjunhuang.codeepiphany.database.tables.SolutionSubmission.SolutionSubmissionPath;
import com.wenjunhuang.codeepiphany.database.tables.records.ChallengeLanguageRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChallengeLanguage extends TableImpl<ChallengeLanguageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>challenge_language</code>
     */
    public static final ChallengeLanguage CHALLENGE_LANGUAGE = new ChallengeLanguage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChallengeLanguageRecord> getRecordType() {
        return ChallengeLanguageRecord.class;
    }

    /**
     * The column <code>challenge_language.challengeId</code>.
     */
    public final TableField<ChallengeLanguageRecord, Long> CHALLENGEID = createField(DSL.name("challengeId"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>challenge_language.language</code>.
     */
    public final TableField<ChallengeLanguageRecord, String> LANGUAGE = createField(DSL.name("language"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>challenge_language.codeTemplate</code>.
     */
    public final TableField<ChallengeLanguageRecord, String> CODETEMPLATE = createField(DSL.name("codeTemplate"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>challenge_language.id</code>.
     */
    public final TableField<ChallengeLanguageRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>challenge_language.languageVersion</code>.
     */
    public final TableField<ChallengeLanguageRecord, String> LANGUAGEVERSION = createField(DSL.name("languageVersion"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("''"), SQLDataType.CLOB)), this, "");

    private ChallengeLanguage(Name alias, Table<ChallengeLanguageRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ChallengeLanguage(Name alias, Table<ChallengeLanguageRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>challenge_language</code> table reference
     */
    public ChallengeLanguage(String alias) {
        this(DSL.name(alias), CHALLENGE_LANGUAGE);
    }

    /**
     * Create an aliased <code>challenge_language</code> table reference
     */
    public ChallengeLanguage(Name alias) {
        this(alias, CHALLENGE_LANGUAGE);
    }

    /**
     * Create a <code>challenge_language</code> table reference
     */
    public ChallengeLanguage() {
        this(DSL.name("challenge_language"), null);
    }

    public <O extends Record> ChallengeLanguage(Table<O> path, ForeignKey<O, ChallengeLanguageRecord> childPath, InverseForeignKey<O, ChallengeLanguageRecord> parentPath) {
        super(path, childPath, parentPath, CHALLENGE_LANGUAGE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ChallengeLanguagePath extends ChallengeLanguage implements Path<ChallengeLanguageRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ChallengeLanguagePath(Table<O> path, ForeignKey<O, ChallengeLanguageRecord> childPath, InverseForeignKey<O, ChallengeLanguageRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ChallengeLanguagePath(Name alias, Table<ChallengeLanguageRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ChallengeLanguagePath as(String alias) {
            return new ChallengeLanguagePath(DSL.name(alias), this);
        }

        @Override
        public ChallengeLanguagePath as(Name alias) {
            return new ChallengeLanguagePath(alias, this);
        }

        @Override
        public ChallengeLanguagePath as(Table<?> alias) {
            return new ChallengeLanguagePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.CHALLENGE_LANGUAGE_CHALLENGEID_LANGUAGE_UINDEX);
    }

    @Override
    public UniqueKey<ChallengeLanguageRecord> getPrimaryKey() {
        return Keys.CHALLENGE_LANGUAGE__PK_CHALLENGE_LANGUAGE;
    }

    @Override
    public List<ForeignKey<ChallengeLanguageRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CHALLENGE_LANGUAGE__FK_CHALLENGE_LANGUAGE_PK_CHALLENGE);
    }

    private transient ChallengePath _challenge;

    /**
     * Get the implicit join path to the <code>challenge</code> table.
     */
    public ChallengePath challenge() {
        if (_challenge == null)
            _challenge = new ChallengePath(this, Keys.CHALLENGE_LANGUAGE__FK_CHALLENGE_LANGUAGE_PK_CHALLENGE, null);

        return _challenge;
    }

    private transient HackerrankChallengeLanguagePath _hackerrankChallengeLanguage;

    /**
     * Get the implicit to-many join path to the
     * <code>hackerrank_challenge_language</code> table
     */
    public HackerrankChallengeLanguagePath hackerrankChallengeLanguage() {
        if (_hackerrankChallengeLanguage == null)
            _hackerrankChallengeLanguage = new HackerrankChallengeLanguagePath(this, null, Keys.HACKERRANK_CHALLENGE_LANGUAGE__FK_HACKERRANK_CHALLENGE_LANGUAGE_PK_CHALLENGE_LANGUAGE.getInverseKey());

        return _hackerrankChallengeLanguage;
    }

    private transient SolutionSubmissionPath _solutionSubmission;

    /**
     * Get the implicit to-many join path to the
     * <code>solution_submission</code> table
     */
    public SolutionSubmissionPath solutionSubmission() {
        if (_solutionSubmission == null)
            _solutionSubmission = new SolutionSubmissionPath(this, null, Keys.SOLUTION_SUBMISSION__FK_SOLUTION_SUBMISSION_PK_CHALLENGE_LANGUAGE.getInverseKey());

        return _solutionSubmission;
    }

    @Override
    public ChallengeLanguage as(String alias) {
        return new ChallengeLanguage(DSL.name(alias), this);
    }

    @Override
    public ChallengeLanguage as(Name alias) {
        return new ChallengeLanguage(alias, this);
    }

    @Override
    public ChallengeLanguage as(Table<?> alias) {
        return new ChallengeLanguage(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ChallengeLanguage rename(String name) {
        return new ChallengeLanguage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ChallengeLanguage rename(Name name) {
        return new ChallengeLanguage(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ChallengeLanguage rename(Table<?> name) {
        return new ChallengeLanguage(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChallengeLanguage where(Condition condition) {
        return new ChallengeLanguage(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChallengeLanguage where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChallengeLanguage where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChallengeLanguage where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChallengeLanguage where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChallengeLanguage where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChallengeLanguage where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChallengeLanguage where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChallengeLanguage whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChallengeLanguage whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
