/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables;


import com.wenjunhuang.codeepiphany.database.DefaultSchema;
import com.wenjunhuang.codeepiphany.database.Keys;
import com.wenjunhuang.codeepiphany.database.tables.HackerrankChallenge.HackerrankChallengePath;
import com.wenjunhuang.codeepiphany.database.tables.records.ChallengeRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Challenge extends TableImpl<ChallengeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>challenge</code>
     */
    public static final Challenge CHALLENGE = new Challenge();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChallengeRecord> getRecordType() {
        return ChallengeRecord.class;
    }

    /**
     * The column <code>challenge.id</code>.
     */
    public final TableField<ChallengeRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>challenge.title</code>.
     */
    public final TableField<ChallengeRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>challenge.slug</code>.
     */
    public final TableField<ChallengeRecord, String> SLUG = createField(DSL.name("slug"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>challenge.dojo</code>.
     */
    public final TableField<ChallengeRecord, String> DOJO = createField(DSL.name("dojo"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>challenge.dojoId</code>.
     */
    public final TableField<ChallengeRecord, String> DOJOID = createField(DSL.name("dojoId"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>challenge.difficulty</code>.
     */
    public final TableField<ChallengeRecord, String> DIFFICULTY = createField(DSL.name("difficulty"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>challenge.language</code>.
     */
    public final TableField<ChallengeRecord, String> LANGUAGE = createField(DSL.name("language"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>challenge.description</code>.
     */
    public final TableField<ChallengeRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>challenge.codeTemplate</code>.
     */
    public final TableField<ChallengeRecord, String> CODETEMPLATE = createField(DSL.name("codeTemplate"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>challenge.tags</code>.
     */
    public final TableField<ChallengeRecord, String> TAGS = createField(DSL.name("tags"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>challenge.remark</code>.
     */
    public final TableField<ChallengeRecord, String> REMARK = createField(DSL.name("remark"), SQLDataType.CLOB, this, "");

    private Challenge(Name alias, Table<ChallengeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Challenge(Name alias, Table<ChallengeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>challenge</code> table reference
     */
    public Challenge(String alias) {
        this(DSL.name(alias), CHALLENGE);
    }

    /**
     * Create an aliased <code>challenge</code> table reference
     */
    public Challenge(Name alias) {
        this(alias, CHALLENGE);
    }

    /**
     * Create a <code>challenge</code> table reference
     */
    public Challenge() {
        this(DSL.name("challenge"), null);
    }

    public <O extends Record> Challenge(Table<O> path, ForeignKey<O, ChallengeRecord> childPath, InverseForeignKey<O, ChallengeRecord> parentPath) {
        super(path, childPath, parentPath, CHALLENGE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ChallengePath extends Challenge implements Path<ChallengeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ChallengePath(Table<O> path, ForeignKey<O, ChallengeRecord> childPath, InverseForeignKey<O, ChallengeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ChallengePath(Name alias, Table<ChallengeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ChallengePath as(String alias) {
            return new ChallengePath(DSL.name(alias), this);
        }

        @Override
        public ChallengePath as(Name alias) {
            return new ChallengePath(alias, this);
        }

        @Override
        public ChallengePath as(Table<?> alias) {
            return new ChallengePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<ChallengeRecord> getPrimaryKey() {
        return Keys.CHALLENGE__PK_CHALLENGE;
    }

    private transient HackerrankChallengePath _hackerrankChallenge;

    /**
     * Get the implicit to-many join path to the
     * <code>hackerrank_challenge</code> table
     */
    public HackerrankChallengePath hackerrankChallenge() {
        if (_hackerrankChallenge == null)
            _hackerrankChallenge = new HackerrankChallengePath(this, null, Keys.HACKERRANK_CHALLENGE__FK_HACKERRANK_CHALLENGE_PK_CHALLENGE.getInverseKey());

        return _hackerrankChallenge;
    }

    @Override
    public Challenge as(String alias) {
        return new Challenge(DSL.name(alias), this);
    }

    @Override
    public Challenge as(Name alias) {
        return new Challenge(alias, this);
    }

    @Override
    public Challenge as(Table<?> alias) {
        return new Challenge(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Challenge rename(String name) {
        return new Challenge(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Challenge rename(Name name) {
        return new Challenge(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Challenge rename(Table<?> name) {
        return new Challenge(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Challenge where(Condition condition) {
        return new Challenge(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Challenge where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Challenge where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Challenge where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Challenge where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Challenge where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Challenge where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Challenge where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Challenge whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Challenge whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
