/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables;


import com.wenjunhuang.codeepiphany.database.DefaultSchema;
import com.wenjunhuang.codeepiphany.database.tables.records.CodeforcesTagsFtsRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CodeforcesTagsFts extends TableImpl<CodeforcesTagsFtsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>codeforces_tags_fts</code>
     */
    public static final CodeforcesTagsFts CODEFORCES_TAGS_FTS = new CodeforcesTagsFts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CodeforcesTagsFtsRecord> getRecordType() {
        return CodeforcesTagsFtsRecord.class;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<CodeforcesTagsFtsRecord, Object> TAGS = createField(DSL.name("tags"), org.jooq.impl.SQLDataType.OTHER, this, "");

    private CodeforcesTagsFts(Name alias, Table<CodeforcesTagsFtsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CodeforcesTagsFts(Name alias, Table<CodeforcesTagsFtsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>codeforces_tags_fts</code> table reference
     */
    public CodeforcesTagsFts(String alias) {
        this(DSL.name(alias), CODEFORCES_TAGS_FTS);
    }

    /**
     * Create an aliased <code>codeforces_tags_fts</code> table reference
     */
    public CodeforcesTagsFts(Name alias) {
        this(alias, CODEFORCES_TAGS_FTS);
    }

    /**
     * Create a <code>codeforces_tags_fts</code> table reference
     */
    public CodeforcesTagsFts() {
        this(DSL.name("codeforces_tags_fts"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public CodeforcesTagsFts as(String alias) {
        return new CodeforcesTagsFts(DSL.name(alias), this);
    }

    @Override
    public CodeforcesTagsFts as(Name alias) {
        return new CodeforcesTagsFts(alias, this);
    }

    @Override
    public CodeforcesTagsFts as(Table<?> alias) {
        return new CodeforcesTagsFts(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeforcesTagsFts rename(String name) {
        return new CodeforcesTagsFts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeforcesTagsFts rename(Name name) {
        return new CodeforcesTagsFts(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeforcesTagsFts rename(Table<?> name) {
        return new CodeforcesTagsFts(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeforcesTagsFts where(Condition condition) {
        return new CodeforcesTagsFts(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeforcesTagsFts where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeforcesTagsFts where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeforcesTagsFts where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeforcesTagsFts where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeforcesTagsFts where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeforcesTagsFts where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeforcesTagsFts where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeforcesTagsFts whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeforcesTagsFts whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
