/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables;


import com.wenjunhuang.codeepiphany.database.DefaultSchema;
import com.wenjunhuang.codeepiphany.database.Indexes;
import com.wenjunhuang.codeepiphany.database.Keys;
import com.wenjunhuang.codeepiphany.database.tables.records.CodeforcesProblemsetsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CodeforcesProblemsets extends TableImpl<CodeforcesProblemsetsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>codeforces_problemsets</code>
     */
    public static final CodeforcesProblemsets CODEFORCES_PROBLEMSETS = new CodeforcesProblemsets();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CodeforcesProblemsetsRecord> getRecordType() {
        return CodeforcesProblemsetsRecord.class;
    }

    /**
     * The column <code>codeforces_problemsets.id</code>.
     */
    public final TableField<CodeforcesProblemsetsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>codeforces_problemsets.contestId</code>.
     */
    public final TableField<CodeforcesProblemsetsRecord, Long> CONTESTID = createField(DSL.name("contestId"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>codeforces_problemsets.solvedCount</code>.
     */
    public final TableField<CodeforcesProblemsetsRecord, Integer> SOLVEDCOUNT = createField(DSL.name("solvedCount"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>codeforces_problemsets.lastUpdateDateTime</code>.
     */
    public final TableField<CodeforcesProblemsetsRecord, LocalDateTime> LASTUPDATEDATETIME = createField(DSL.name("lastUpdateDateTime"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>codeforces_problemsets.rating</code>.
     */
    public final TableField<CodeforcesProblemsetsRecord, Integer> RATING = createField(DSL.name("rating"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>codeforces_problemsets.points</code>.
     */
    public final TableField<CodeforcesProblemsetsRecord, Float> POINTS = createField(DSL.name("points"), SQLDataType.REAL, this, "");

    /**
     * The column <code>codeforces_problemsets.index</code>.
     */
    public final TableField<CodeforcesProblemsetsRecord, String> INDEX = createField(DSL.name("index"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>codeforces_problemsets.name</code>.
     */
    public final TableField<CodeforcesProblemsetsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>codeforces_problemsets.type</code>.
     */
    public final TableField<CodeforcesProblemsetsRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>codeforces_problemsets.contestIdIndex</code>.
     */
    public final TableField<CodeforcesProblemsetsRecord, String> CONTESTIDINDEX = createField(DSL.name("contestIdIndex"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>codeforces_problemsets.tags</code>.
     */
    public final TableField<CodeforcesProblemsetsRecord, String> TAGS = createField(DSL.name("tags"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>codeforces_problemsets.problemsetName</code>.
     */
    public final TableField<CodeforcesProblemsetsRecord, String> PROBLEMSETNAME = createField(DSL.name("problemsetName"), SQLDataType.CLOB, this, "");

    private CodeforcesProblemsets(Name alias, Table<CodeforcesProblemsetsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CodeforcesProblemsets(Name alias, Table<CodeforcesProblemsetsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>codeforces_problemsets</code> table reference
     */
    public CodeforcesProblemsets(String alias) {
        this(DSL.name(alias), CODEFORCES_PROBLEMSETS);
    }

    /**
     * Create an aliased <code>codeforces_problemsets</code> table reference
     */
    public CodeforcesProblemsets(Name alias) {
        this(alias, CODEFORCES_PROBLEMSETS);
    }

    /**
     * Create a <code>codeforces_problemsets</code> table reference
     */
    public CodeforcesProblemsets() {
        this(DSL.name("codeforces_problemsets"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.CODEFORCES_PROBLEMSETS_CONTESTID_INDEX_INDEX);
    }

    @Override
    public UniqueKey<CodeforcesProblemsetsRecord> getPrimaryKey() {
        return Keys.CODEFORCES_PROBLEMSETS__PK_CODEFORCES_PROBLEMSETS;
    }

    @Override
    public CodeforcesProblemsets as(String alias) {
        return new CodeforcesProblemsets(DSL.name(alias), this);
    }

    @Override
    public CodeforcesProblemsets as(Name alias) {
        return new CodeforcesProblemsets(alias, this);
    }

    @Override
    public CodeforcesProblemsets as(Table<?> alias) {
        return new CodeforcesProblemsets(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeforcesProblemsets rename(String name) {
        return new CodeforcesProblemsets(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeforcesProblemsets rename(Name name) {
        return new CodeforcesProblemsets(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeforcesProblemsets rename(Table<?> name) {
        return new CodeforcesProblemsets(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeforcesProblemsets where(Condition condition) {
        return new CodeforcesProblemsets(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeforcesProblemsets where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeforcesProblemsets where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeforcesProblemsets where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeforcesProblemsets where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeforcesProblemsets where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeforcesProblemsets where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeforcesProblemsets where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeforcesProblemsets whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeforcesProblemsets whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
