/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables;


import com.wenjunhuang.codeepiphany.database.DefaultSchema;
import com.wenjunhuang.codeepiphany.database.Keys;
import com.wenjunhuang.codeepiphany.database.tables.Challenge.ChallengePath;
import com.wenjunhuang.codeepiphany.database.tables.records.CodeforcesChallengeRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CodeforcesChallenge extends TableImpl<CodeforcesChallengeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>codeforces_challenge</code>
     */
    public static final CodeforcesChallenge CODEFORCES_CHALLENGE = new CodeforcesChallenge();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CodeforcesChallengeRecord> getRecordType() {
        return CodeforcesChallengeRecord.class;
    }

    /**
     * The column <code>codeforces_challenge.id</code>.
     */
    public final TableField<CodeforcesChallengeRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>codeforces_challenge.contestId</code>.
     */
    public final TableField<CodeforcesChallengeRecord, Long> CONTESTID = createField(DSL.name("contestId"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>codeforces_challenge.index</code>.
     */
    public final TableField<CodeforcesChallengeRecord, String> INDEX = createField(DSL.name("index"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>codeforces_challenge.problemsetName</code>.
     */
    public final TableField<CodeforcesChallengeRecord, String> PROBLEMSETNAME = createField(DSL.name("problemsetName"), SQLDataType.CLOB, this, "");

    private CodeforcesChallenge(Name alias, Table<CodeforcesChallengeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CodeforcesChallenge(Name alias, Table<CodeforcesChallengeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>codeforces_challenge</code> table reference
     */
    public CodeforcesChallenge(String alias) {
        this(DSL.name(alias), CODEFORCES_CHALLENGE);
    }

    /**
     * Create an aliased <code>codeforces_challenge</code> table reference
     */
    public CodeforcesChallenge(Name alias) {
        this(alias, CODEFORCES_CHALLENGE);
    }

    /**
     * Create a <code>codeforces_challenge</code> table reference
     */
    public CodeforcesChallenge() {
        this(DSL.name("codeforces_challenge"), null);
    }

    public <O extends Record> CodeforcesChallenge(Table<O> path, ForeignKey<O, CodeforcesChallengeRecord> childPath, InverseForeignKey<O, CodeforcesChallengeRecord> parentPath) {
        super(path, childPath, parentPath, CODEFORCES_CHALLENGE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CodeforcesChallengePath extends CodeforcesChallenge implements Path<CodeforcesChallengeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CodeforcesChallengePath(Table<O> path, ForeignKey<O, CodeforcesChallengeRecord> childPath, InverseForeignKey<O, CodeforcesChallengeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CodeforcesChallengePath(Name alias, Table<CodeforcesChallengeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CodeforcesChallengePath as(String alias) {
            return new CodeforcesChallengePath(DSL.name(alias), this);
        }

        @Override
        public CodeforcesChallengePath as(Name alias) {
            return new CodeforcesChallengePath(alias, this);
        }

        @Override
        public CodeforcesChallengePath as(Table<?> alias) {
            return new CodeforcesChallengePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<CodeforcesChallengeRecord> getPrimaryKey() {
        return Keys.CODEFORCES_CHALLENGE__PK_CODEFORCES_CHALLENGE;
    }

    @Override
    public List<ForeignKey<CodeforcesChallengeRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CODEFORCES_CHALLENGE__FK_CODEFORCES_CHALLENGE_PK_CHALLENGE);
    }

    private transient ChallengePath _challenge;

    /**
     * Get the implicit join path to the <code>challenge</code> table.
     */
    public ChallengePath challenge() {
        if (_challenge == null)
            _challenge = new ChallengePath(this, Keys.CODEFORCES_CHALLENGE__FK_CODEFORCES_CHALLENGE_PK_CHALLENGE, null);

        return _challenge;
    }

    @Override
    public CodeforcesChallenge as(String alias) {
        return new CodeforcesChallenge(DSL.name(alias), this);
    }

    @Override
    public CodeforcesChallenge as(Name alias) {
        return new CodeforcesChallenge(alias, this);
    }

    @Override
    public CodeforcesChallenge as(Table<?> alias) {
        return new CodeforcesChallenge(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeforcesChallenge rename(String name) {
        return new CodeforcesChallenge(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeforcesChallenge rename(Name name) {
        return new CodeforcesChallenge(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeforcesChallenge rename(Table<?> name) {
        return new CodeforcesChallenge(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeforcesChallenge where(Condition condition) {
        return new CodeforcesChallenge(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeforcesChallenge where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeforcesChallenge where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeforcesChallenge where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeforcesChallenge where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeforcesChallenge where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeforcesChallenge where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeforcesChallenge where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeforcesChallenge whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeforcesChallenge whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
