/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables;


import com.wenjunhuang.codeepiphany.database.DefaultSchema;
import com.wenjunhuang.codeepiphany.database.tables.records.CodeforcesProblemsetsFtsRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CodeforcesProblemsetsFts extends TableImpl<CodeforcesProblemsetsFtsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>codeforces_problemsets_fts</code>
     */
    public static final CodeforcesProblemsetsFts CODEFORCES_PROBLEMSETS_FTS = new CodeforcesProblemsetsFts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CodeforcesProblemsetsFtsRecord> getRecordType() {
        return CodeforcesProblemsetsFtsRecord.class;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<CodeforcesProblemsetsFtsRecord, Object> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<CodeforcesProblemsetsFtsRecord, Object> CONTESTID = createField(DSL.name("contestId"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<CodeforcesProblemsetsFtsRecord, Object> SOLVEDCOUNT = createField(DSL.name("solvedCount"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * The column <code>codeforces_problemsets_fts.lastUpdateDateTime</code>.
     */
    public final TableField<CodeforcesProblemsetsFtsRecord, LocalDateTime> LASTUPDATEDATETIME = createField(DSL.name("lastUpdateDateTime"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<CodeforcesProblemsetsFtsRecord, Object> RATING = createField(DSL.name("rating"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<CodeforcesProblemsetsFtsRecord, Object> POINTS = createField(DSL.name("points"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<CodeforcesProblemsetsFtsRecord, Object> INDEX = createField(DSL.name("index"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<CodeforcesProblemsetsFtsRecord, Object> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<CodeforcesProblemsetsFtsRecord, Object> TYPE = createField(DSL.name("type"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<CodeforcesProblemsetsFtsRecord, Object> CONTESTIDINDEX = createField(DSL.name("contestIdIndex"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<CodeforcesProblemsetsFtsRecord, Object> TAGS = createField(DSL.name("tags"), org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<CodeforcesProblemsetsFtsRecord, Object> PROBLEMSETNAME = createField(DSL.name("problemsetName"), org.jooq.impl.SQLDataType.OTHER, this, "");

    private CodeforcesProblemsetsFts(Name alias, Table<CodeforcesProblemsetsFtsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CodeforcesProblemsetsFts(Name alias, Table<CodeforcesProblemsetsFtsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>codeforces_problemsets_fts</code> table reference
     */
    public CodeforcesProblemsetsFts(String alias) {
        this(DSL.name(alias), CODEFORCES_PROBLEMSETS_FTS);
    }

    /**
     * Create an aliased <code>codeforces_problemsets_fts</code> table reference
     */
    public CodeforcesProblemsetsFts(Name alias) {
        this(alias, CODEFORCES_PROBLEMSETS_FTS);
    }

    /**
     * Create a <code>codeforces_problemsets_fts</code> table reference
     */
    public CodeforcesProblemsetsFts() {
        this(DSL.name("codeforces_problemsets_fts"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public CodeforcesProblemsetsFts as(String alias) {
        return new CodeforcesProblemsetsFts(DSL.name(alias), this);
    }

    @Override
    public CodeforcesProblemsetsFts as(Name alias) {
        return new CodeforcesProblemsetsFts(alias, this);
    }

    @Override
    public CodeforcesProblemsetsFts as(Table<?> alias) {
        return new CodeforcesProblemsetsFts(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeforcesProblemsetsFts rename(String name) {
        return new CodeforcesProblemsetsFts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeforcesProblemsetsFts rename(Name name) {
        return new CodeforcesProblemsetsFts(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CodeforcesProblemsetsFts rename(Table<?> name) {
        return new CodeforcesProblemsetsFts(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeforcesProblemsetsFts where(Condition condition) {
        return new CodeforcesProblemsetsFts(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeforcesProblemsetsFts where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeforcesProblemsetsFts where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeforcesProblemsetsFts where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeforcesProblemsetsFts where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeforcesProblemsetsFts where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeforcesProblemsetsFts where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CodeforcesProblemsetsFts where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeforcesProblemsetsFts whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CodeforcesProblemsetsFts whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
