/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables;


import com.wenjunhuang.codeepiphany.database.DefaultSchema;
import com.wenjunhuang.codeepiphany.database.Keys;
import com.wenjunhuang.codeepiphany.database.tables.SolutionSubmission.SolutionSubmissionPath;
import com.wenjunhuang.codeepiphany.database.tables.records.HackerrankSolutionSubmissionResultRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HackerrankSolutionSubmissionResult extends TableImpl<HackerrankSolutionSubmissionResultRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>hackerrank_solution_submission_result</code>
     */
    public static final HackerrankSolutionSubmissionResult HACKERRANK_SOLUTION_SUBMISSION_RESULT = new HackerrankSolutionSubmissionResult();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HackerrankSolutionSubmissionResultRecord> getRecordType() {
        return HackerrankSolutionSubmissionResultRecord.class;
    }

    /**
     * The column <code>hackerrank_solution_submission_result.id</code>.
     */
    public final TableField<HackerrankSolutionSubmissionResultRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>hackerrank_solution_submission_result.state</code>.
     */
    public final TableField<HackerrankSolutionSubmissionResultRecord, String> STATE = createField(DSL.name("state"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>hackerrank_solution_submission_result.message</code>.
     */
    public final TableField<HackerrankSolutionSubmissionResultRecord, String> MESSAGE = createField(DSL.name("message"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>hackerrank_solution_submission_result.num</code>.
     */
    public final TableField<HackerrankSolutionSubmissionResultRecord, Integer> NUM = createField(DSL.name("num"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>hackerrank_solution_submission_result.stdIn</code>.
     */
    public final TableField<HackerrankSolutionSubmissionResultRecord, String> STDIN = createField(DSL.name("stdIn"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>hackerrank_solution_submission_result.expectedOutput</code>.
     */
    public final TableField<HackerrankSolutionSubmissionResultRecord, String> EXPECTEDOUTPUT = createField(DSL.name("expectedOutput"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>hackerrank_solution_submission_result.submissionId</code>.
     */
    public final TableField<HackerrankSolutionSubmissionResultRecord, Integer> SUBMISSIONID = createField(DSL.name("submissionId"), SQLDataType.INTEGER.nullable(false), this, "");

    private HackerrankSolutionSubmissionResult(Name alias, Table<HackerrankSolutionSubmissionResultRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private HackerrankSolutionSubmissionResult(Name alias, Table<HackerrankSolutionSubmissionResultRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>hackerrank_solution_submission_result</code>
     * table reference
     */
    public HackerrankSolutionSubmissionResult(String alias) {
        this(DSL.name(alias), HACKERRANK_SOLUTION_SUBMISSION_RESULT);
    }

    /**
     * Create an aliased <code>hackerrank_solution_submission_result</code>
     * table reference
     */
    public HackerrankSolutionSubmissionResult(Name alias) {
        this(alias, HACKERRANK_SOLUTION_SUBMISSION_RESULT);
    }

    /**
     * Create a <code>hackerrank_solution_submission_result</code> table
     * reference
     */
    public HackerrankSolutionSubmissionResult() {
        this(DSL.name("hackerrank_solution_submission_result"), null);
    }

    public <O extends Record> HackerrankSolutionSubmissionResult(Table<O> path, ForeignKey<O, HackerrankSolutionSubmissionResultRecord> childPath, InverseForeignKey<O, HackerrankSolutionSubmissionResultRecord> parentPath) {
        super(path, childPath, parentPath, HACKERRANK_SOLUTION_SUBMISSION_RESULT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class HackerrankSolutionSubmissionResultPath extends HackerrankSolutionSubmissionResult implements Path<HackerrankSolutionSubmissionResultRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> HackerrankSolutionSubmissionResultPath(Table<O> path, ForeignKey<O, HackerrankSolutionSubmissionResultRecord> childPath, InverseForeignKey<O, HackerrankSolutionSubmissionResultRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private HackerrankSolutionSubmissionResultPath(Name alias, Table<HackerrankSolutionSubmissionResultRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public HackerrankSolutionSubmissionResultPath as(String alias) {
            return new HackerrankSolutionSubmissionResultPath(DSL.name(alias), this);
        }

        @Override
        public HackerrankSolutionSubmissionResultPath as(Name alias) {
            return new HackerrankSolutionSubmissionResultPath(alias, this);
        }

        @Override
        public HackerrankSolutionSubmissionResultPath as(Table<?> alias) {
            return new HackerrankSolutionSubmissionResultPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<HackerrankSolutionSubmissionResultRecord, Integer> getIdentity() {
        return (Identity<HackerrankSolutionSubmissionResultRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<HackerrankSolutionSubmissionResultRecord> getPrimaryKey() {
        return Keys.HACKERRANK_SOLUTION_SUBMISSION_RESULT__PK_HACKERRANK_SOLUTION_SUBMISSION_RESULT;
    }

    @Override
    public List<ForeignKey<HackerrankSolutionSubmissionResultRecord, ?>> getReferences() {
        return Arrays.asList(Keys.HACKERRANK_SOLUTION_SUBMISSION_RESULT__FK_HACKERRANK_SOLUTION_SUBMISSION_RESULT_PK_SOLUTION_SUBMISSION);
    }

    private transient SolutionSubmissionPath _solutionSubmission;

    /**
     * Get the implicit join path to the <code>solution_submission</code> table.
     */
    public SolutionSubmissionPath solutionSubmission() {
        if (_solutionSubmission == null)
            _solutionSubmission = new SolutionSubmissionPath(this, Keys.HACKERRANK_SOLUTION_SUBMISSION_RESULT__FK_HACKERRANK_SOLUTION_SUBMISSION_RESULT_PK_SOLUTION_SUBMISSION, null);

        return _solutionSubmission;
    }

    @Override
    public HackerrankSolutionSubmissionResult as(String alias) {
        return new HackerrankSolutionSubmissionResult(DSL.name(alias), this);
    }

    @Override
    public HackerrankSolutionSubmissionResult as(Name alias) {
        return new HackerrankSolutionSubmissionResult(alias, this);
    }

    @Override
    public HackerrankSolutionSubmissionResult as(Table<?> alias) {
        return new HackerrankSolutionSubmissionResult(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public HackerrankSolutionSubmissionResult rename(String name) {
        return new HackerrankSolutionSubmissionResult(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public HackerrankSolutionSubmissionResult rename(Name name) {
        return new HackerrankSolutionSubmissionResult(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public HackerrankSolutionSubmissionResult rename(Table<?> name) {
        return new HackerrankSolutionSubmissionResult(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HackerrankSolutionSubmissionResult where(Condition condition) {
        return new HackerrankSolutionSubmissionResult(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HackerrankSolutionSubmissionResult where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HackerrankSolutionSubmissionResult where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HackerrankSolutionSubmissionResult where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HackerrankSolutionSubmissionResult where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HackerrankSolutionSubmissionResult where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HackerrankSolutionSubmissionResult where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HackerrankSolutionSubmissionResult where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HackerrankSolutionSubmissionResult whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HackerrankSolutionSubmissionResult whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
