/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables;


import com.wenjunhuang.codeepiphany.database.DefaultSchema;
import com.wenjunhuang.codeepiphany.database.Keys;
import com.wenjunhuang.codeepiphany.database.tables.Challenge.ChallengePath;
import com.wenjunhuang.codeepiphany.database.tables.records.HackerrankChallengeRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HackerrankChallenge extends TableImpl<HackerrankChallengeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>hackerrank_challenge</code>
     */
    public static final HackerrankChallenge HACKERRANK_CHALLENGE = new HackerrankChallenge();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HackerrankChallengeRecord> getRecordType() {
        return HackerrankChallengeRecord.class;
    }

    /**
     * The column <code>hackerrank_challenge.challengeId</code>.
     */
    public final TableField<HackerrankChallengeRecord, Integer> CHALLENGEID = createField(DSL.name("challengeId"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>hackerrank_challenge.contestSlug</code>.
     */
    public final TableField<HackerrankChallengeRecord, String> CONTESTSLUG = createField(DSL.name("contestSlug"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>hackerrank_challenge.contest</code>.
     */
    public final TableField<HackerrankChallengeRecord, String> CONTEST = createField(DSL.name("contest"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>hackerrank_challenge.codeHeader</code>.
     */
    public final TableField<HackerrankChallengeRecord, String> CODEHEADER = createField(DSL.name("codeHeader"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>hackerrank_challenge.codeTemplate</code>.
     */
    public final TableField<HackerrankChallengeRecord, String> CODETEMPLATE = createField(DSL.name("codeTemplate"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>hackerrank_challenge.codeTail</code>.
     */
    public final TableField<HackerrankChallengeRecord, String> CODETAIL = createField(DSL.name("codeTail"), SQLDataType.CLOB.nullable(false), this, "");

    private HackerrankChallenge(Name alias, Table<HackerrankChallengeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private HackerrankChallenge(Name alias, Table<HackerrankChallengeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>hackerrank_challenge</code> table reference
     */
    public HackerrankChallenge(String alias) {
        this(DSL.name(alias), HACKERRANK_CHALLENGE);
    }

    /**
     * Create an aliased <code>hackerrank_challenge</code> table reference
     */
    public HackerrankChallenge(Name alias) {
        this(alias, HACKERRANK_CHALLENGE);
    }

    /**
     * Create a <code>hackerrank_challenge</code> table reference
     */
    public HackerrankChallenge() {
        this(DSL.name("hackerrank_challenge"), null);
    }

    public <O extends Record> HackerrankChallenge(Table<O> path, ForeignKey<O, HackerrankChallengeRecord> childPath, InverseForeignKey<O, HackerrankChallengeRecord> parentPath) {
        super(path, childPath, parentPath, HACKERRANK_CHALLENGE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class HackerrankChallengePath extends HackerrankChallenge implements Path<HackerrankChallengeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> HackerrankChallengePath(Table<O> path, ForeignKey<O, HackerrankChallengeRecord> childPath, InverseForeignKey<O, HackerrankChallengeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private HackerrankChallengePath(Name alias, Table<HackerrankChallengeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public HackerrankChallengePath as(String alias) {
            return new HackerrankChallengePath(DSL.name(alias), this);
        }

        @Override
        public HackerrankChallengePath as(Name alias) {
            return new HackerrankChallengePath(alias, this);
        }

        @Override
        public HackerrankChallengePath as(Table<?> alias) {
            return new HackerrankChallengePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<HackerrankChallengeRecord> getPrimaryKey() {
        return Keys.HACKERRANK_CHALLENGE__PK_HACKERRANK_CHALLENGE;
    }

    @Override
    public List<ForeignKey<HackerrankChallengeRecord, ?>> getReferences() {
        return Arrays.asList(Keys.HACKERRANK_CHALLENGE__FK_HACKERRANK_CHALLENGE_PK_CHALLENGE);
    }

    private transient ChallengePath _challenge;

    /**
     * Get the implicit join path to the <code>challenge</code> table.
     */
    public ChallengePath challenge() {
        if (_challenge == null)
            _challenge = new ChallengePath(this, Keys.HACKERRANK_CHALLENGE__FK_HACKERRANK_CHALLENGE_PK_CHALLENGE, null);

        return _challenge;
    }

    @Override
    public HackerrankChallenge as(String alias) {
        return new HackerrankChallenge(DSL.name(alias), this);
    }

    @Override
    public HackerrankChallenge as(Name alias) {
        return new HackerrankChallenge(alias, this);
    }

    @Override
    public HackerrankChallenge as(Table<?> alias) {
        return new HackerrankChallenge(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public HackerrankChallenge rename(String name) {
        return new HackerrankChallenge(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public HackerrankChallenge rename(Name name) {
        return new HackerrankChallenge(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public HackerrankChallenge rename(Table<?> name) {
        return new HackerrankChallenge(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HackerrankChallenge where(Condition condition) {
        return new HackerrankChallenge(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HackerrankChallenge where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HackerrankChallenge where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HackerrankChallenge where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HackerrankChallenge where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HackerrankChallenge where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HackerrankChallenge where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HackerrankChallenge where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HackerrankChallenge whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HackerrankChallenge whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
