/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables;


import com.wenjunhuang.codeepiphany.database.DefaultSchema;
import com.wenjunhuang.codeepiphany.database.Keys;
import com.wenjunhuang.codeepiphany.database.tables.ChallengeLanguage.ChallengeLanguagePath;
import com.wenjunhuang.codeepiphany.database.tables.records.HackerrankChallengeLanguageRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HackerrankChallengeLanguage extends TableImpl<HackerrankChallengeLanguageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>hackerrank_challenge_language</code>
     */
    public static final HackerrankChallengeLanguage HACKERRANK_CHALLENGE_LANGUAGE = new HackerrankChallengeLanguage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HackerrankChallengeLanguageRecord> getRecordType() {
        return HackerrankChallengeLanguageRecord.class;
    }

    /**
     * The column <code>hackerrank_challenge_language.id</code>.
     */
    public final TableField<HackerrankChallengeLanguageRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>hackerrank_challenge_language.codeHeader</code>.
     */
    public final TableField<HackerrankChallengeLanguageRecord, String> CODEHEADER = createField(DSL.name("codeHeader"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>hackerrank_challenge_language.codeTemplate</code>.
     */
    public final TableField<HackerrankChallengeLanguageRecord, String> CODETEMPLATE = createField(DSL.name("codeTemplate"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>hackerrank_challenge_language.codeTail</code>.
     */
    public final TableField<HackerrankChallengeLanguageRecord, String> CODETAIL = createField(DSL.name("codeTail"), SQLDataType.CLOB.nullable(false), this, "");

    private HackerrankChallengeLanguage(Name alias, Table<HackerrankChallengeLanguageRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private HackerrankChallengeLanguage(Name alias, Table<HackerrankChallengeLanguageRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>hackerrank_challenge_language</code> table
     * reference
     */
    public HackerrankChallengeLanguage(String alias) {
        this(DSL.name(alias), HACKERRANK_CHALLENGE_LANGUAGE);
    }

    /**
     * Create an aliased <code>hackerrank_challenge_language</code> table
     * reference
     */
    public HackerrankChallengeLanguage(Name alias) {
        this(alias, HACKERRANK_CHALLENGE_LANGUAGE);
    }

    /**
     * Create a <code>hackerrank_challenge_language</code> table reference
     */
    public HackerrankChallengeLanguage() {
        this(DSL.name("hackerrank_challenge_language"), null);
    }

    public <O extends Record> HackerrankChallengeLanguage(Table<O> path, ForeignKey<O, HackerrankChallengeLanguageRecord> childPath, InverseForeignKey<O, HackerrankChallengeLanguageRecord> parentPath) {
        super(path, childPath, parentPath, HACKERRANK_CHALLENGE_LANGUAGE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class HackerrankChallengeLanguagePath extends HackerrankChallengeLanguage implements Path<HackerrankChallengeLanguageRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> HackerrankChallengeLanguagePath(Table<O> path, ForeignKey<O, HackerrankChallengeLanguageRecord> childPath, InverseForeignKey<O, HackerrankChallengeLanguageRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private HackerrankChallengeLanguagePath(Name alias, Table<HackerrankChallengeLanguageRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public HackerrankChallengeLanguagePath as(String alias) {
            return new HackerrankChallengeLanguagePath(DSL.name(alias), this);
        }

        @Override
        public HackerrankChallengeLanguagePath as(Name alias) {
            return new HackerrankChallengeLanguagePath(alias, this);
        }

        @Override
        public HackerrankChallengeLanguagePath as(Table<?> alias) {
            return new HackerrankChallengeLanguagePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<HackerrankChallengeLanguageRecord> getPrimaryKey() {
        return Keys.HACKERRANK_CHALLENGE_LANGUAGE__PK_HACKERRANK_CHALLENGE_LANGUAGE;
    }

    @Override
    public List<ForeignKey<HackerrankChallengeLanguageRecord, ?>> getReferences() {
        return Arrays.asList(Keys.HACKERRANK_CHALLENGE_LANGUAGE__FK_HACKERRANK_CHALLENGE_LANGUAGE_PK_CHALLENGE_LANGUAGE);
    }

    private transient ChallengeLanguagePath _challengeLanguage;

    /**
     * Get the implicit join path to the <code>challenge_language</code> table.
     */
    public ChallengeLanguagePath challengeLanguage() {
        if (_challengeLanguage == null)
            _challengeLanguage = new ChallengeLanguagePath(this, Keys.HACKERRANK_CHALLENGE_LANGUAGE__FK_HACKERRANK_CHALLENGE_LANGUAGE_PK_CHALLENGE_LANGUAGE, null);

        return _challengeLanguage;
    }

    @Override
    public HackerrankChallengeLanguage as(String alias) {
        return new HackerrankChallengeLanguage(DSL.name(alias), this);
    }

    @Override
    public HackerrankChallengeLanguage as(Name alias) {
        return new HackerrankChallengeLanguage(alias, this);
    }

    @Override
    public HackerrankChallengeLanguage as(Table<?> alias) {
        return new HackerrankChallengeLanguage(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public HackerrankChallengeLanguage rename(String name) {
        return new HackerrankChallengeLanguage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public HackerrankChallengeLanguage rename(Name name) {
        return new HackerrankChallengeLanguage(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public HackerrankChallengeLanguage rename(Table<?> name) {
        return new HackerrankChallengeLanguage(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HackerrankChallengeLanguage where(Condition condition) {
        return new HackerrankChallengeLanguage(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HackerrankChallengeLanguage where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HackerrankChallengeLanguage where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HackerrankChallengeLanguage where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HackerrankChallengeLanguage where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HackerrankChallengeLanguage where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HackerrankChallengeLanguage where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HackerrankChallengeLanguage where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HackerrankChallengeLanguage whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HackerrankChallengeLanguage whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
