/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables;


import com.wenjunhuang.codeepiphany.database.DefaultSchema;
import com.wenjunhuang.codeepiphany.database.Keys;
import com.wenjunhuang.codeepiphany.database.tables.SolutionSubmission.SolutionSubmissionPath;
import com.wenjunhuang.codeepiphany.database.tables.records.HackerrankSubmissionCaseRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HackerrankSubmissionCase extends TableImpl<HackerrankSubmissionCaseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>hackerrank_submission_case</code>
     */
    public static final HackerrankSubmissionCase HACKERRANK_SUBMISSION_CASE = new HackerrankSubmissionCase();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HackerrankSubmissionCaseRecord> getRecordType() {
        return HackerrankSubmissionCaseRecord.class;
    }

    /**
     * The column <code>hackerrank_submission_case.id</code>.
     */
    public final TableField<HackerrankSubmissionCaseRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>hackerrank_submission_case.testcaseMessage</code>.
     */
    public final TableField<HackerrankSubmissionCaseRecord, String> TESTCASEMESSAGE = createField(DSL.name("testcaseMessage"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>hackerrank_submission_case.num</code>.
     */
    public final TableField<HackerrankSubmissionCaseRecord, Integer> NUM = createField(DSL.name("num"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>hackerrank_submission_case.stdIn</code>.
     */
    public final TableField<HackerrankSubmissionCaseRecord, String> STDIN = createField(DSL.name("stdIn"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>hackerrank_submission_case.expectedOutput</code>.
     */
    public final TableField<HackerrankSubmissionCaseRecord, String> EXPECTEDOUTPUT = createField(DSL.name("expectedOutput"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>hackerrank_submission_case.submissionId</code>.
     */
    public final TableField<HackerrankSubmissionCaseRecord, Long> SUBMISSIONID = createField(DSL.name("submissionId"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>hackerrank_submission_case.codecheckerSignal</code>.
     */
    public final TableField<HackerrankSubmissionCaseRecord, Integer> CODECHECKERSIGNAL = createField(DSL.name("codecheckerSignal"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>hackerrank_submission_case.codecheckerTime</code>.
     */
    public final TableField<HackerrankSubmissionCaseRecord, Float> CODECHECKERTIME = createField(DSL.name("codecheckerTime"), SQLDataType.REAL, this, "");

    /**
     * The column <code>hackerrank_submission_case.testcaseStatus</code>.
     */
    public final TableField<HackerrankSubmissionCaseRecord, Integer> TESTCASESTATUS = createField(DSL.name("testcaseStatus"), SQLDataType.INTEGER, this, "");

    private HackerrankSubmissionCase(Name alias, Table<HackerrankSubmissionCaseRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private HackerrankSubmissionCase(Name alias, Table<HackerrankSubmissionCaseRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>hackerrank_submission_case</code> table reference
     */
    public HackerrankSubmissionCase(String alias) {
        this(DSL.name(alias), HACKERRANK_SUBMISSION_CASE);
    }

    /**
     * Create an aliased <code>hackerrank_submission_case</code> table reference
     */
    public HackerrankSubmissionCase(Name alias) {
        this(alias, HACKERRANK_SUBMISSION_CASE);
    }

    /**
     * Create a <code>hackerrank_submission_case</code> table reference
     */
    public HackerrankSubmissionCase() {
        this(DSL.name("hackerrank_submission_case"), null);
    }

    public <O extends Record> HackerrankSubmissionCase(Table<O> path, ForeignKey<O, HackerrankSubmissionCaseRecord> childPath, InverseForeignKey<O, HackerrankSubmissionCaseRecord> parentPath) {
        super(path, childPath, parentPath, HACKERRANK_SUBMISSION_CASE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class HackerrankSubmissionCasePath extends HackerrankSubmissionCase implements Path<HackerrankSubmissionCaseRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> HackerrankSubmissionCasePath(Table<O> path, ForeignKey<O, HackerrankSubmissionCaseRecord> childPath, InverseForeignKey<O, HackerrankSubmissionCaseRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private HackerrankSubmissionCasePath(Name alias, Table<HackerrankSubmissionCaseRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public HackerrankSubmissionCasePath as(String alias) {
            return new HackerrankSubmissionCasePath(DSL.name(alias), this);
        }

        @Override
        public HackerrankSubmissionCasePath as(Name alias) {
            return new HackerrankSubmissionCasePath(alias, this);
        }

        @Override
        public HackerrankSubmissionCasePath as(Table<?> alias) {
            return new HackerrankSubmissionCasePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<HackerrankSubmissionCaseRecord> getPrimaryKey() {
        return Keys.HACKERRANK_SUBMISSION_CASE__PK_HACKERRANK_SUBMISSION_CASE;
    }

    @Override
    public List<ForeignKey<HackerrankSubmissionCaseRecord, ?>> getReferences() {
        return Arrays.asList(Keys.HACKERRANK_SUBMISSION_CASE__FK_HACKERRANK_SUBMISSION_CASE_PK_SOLUTION_SUBMISSION);
    }

    private transient SolutionSubmissionPath _solutionSubmission;

    /**
     * Get the implicit join path to the <code>solution_submission</code> table.
     */
    public SolutionSubmissionPath solutionSubmission() {
        if (_solutionSubmission == null)
            _solutionSubmission = new SolutionSubmissionPath(this, Keys.HACKERRANK_SUBMISSION_CASE__FK_HACKERRANK_SUBMISSION_CASE_PK_SOLUTION_SUBMISSION, null);

        return _solutionSubmission;
    }

    @Override
    public HackerrankSubmissionCase as(String alias) {
        return new HackerrankSubmissionCase(DSL.name(alias), this);
    }

    @Override
    public HackerrankSubmissionCase as(Name alias) {
        return new HackerrankSubmissionCase(alias, this);
    }

    @Override
    public HackerrankSubmissionCase as(Table<?> alias) {
        return new HackerrankSubmissionCase(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public HackerrankSubmissionCase rename(String name) {
        return new HackerrankSubmissionCase(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public HackerrankSubmissionCase rename(Name name) {
        return new HackerrankSubmissionCase(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public HackerrankSubmissionCase rename(Table<?> name) {
        return new HackerrankSubmissionCase(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HackerrankSubmissionCase where(Condition condition) {
        return new HackerrankSubmissionCase(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HackerrankSubmissionCase where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HackerrankSubmissionCase where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HackerrankSubmissionCase where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HackerrankSubmissionCase where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HackerrankSubmissionCase where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HackerrankSubmissionCase where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HackerrankSubmissionCase where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HackerrankSubmissionCase whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HackerrankSubmissionCase whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
