/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables;


import com.wenjunhuang.codeepiphany.database.DefaultSchema;
import com.wenjunhuang.codeepiphany.database.Keys;
import com.wenjunhuang.codeepiphany.database.tables.SolutionSubmission.SolutionSubmissionPath;
import com.wenjunhuang.codeepiphany.database.tables.records.LeetcodeSubmissionRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LeetcodeSubmission extends TableImpl<LeetcodeSubmissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>leetcode_submission</code>
     */
    public static final LeetcodeSubmission LEETCODE_SUBMISSION = new LeetcodeSubmission();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LeetcodeSubmissionRecord> getRecordType() {
        return LeetcodeSubmissionRecord.class;
    }

    /**
     * The column <code>leetcode_submission.id</code>.
     */
    public final TableField<LeetcodeSubmissionRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>leetcode_submission.memory</code>.
     */
    public final TableField<LeetcodeSubmissionRecord, Integer> MEMORY = createField(DSL.name("memory"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>leetcode_submission.totalCorrect</code>.
     */
    public final TableField<LeetcodeSubmissionRecord, Integer> TOTALCORRECT = createField(DSL.name("totalCorrect"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>leetcode_submission.totalTestcases</code>.
     */
    public final TableField<LeetcodeSubmissionRecord, Integer> TOTALTESTCASES = createField(DSL.name("totalTestcases"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>leetcode_submission.statusMemory</code>.
     */
    public final TableField<LeetcodeSubmissionRecord, String> STATUSMEMORY = createField(DSL.name("statusMemory"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>leetcode_submission.runtimePercentile</code>.
     */
    public final TableField<LeetcodeSubmissionRecord, Float> RUNTIMEPERCENTILE = createField(DSL.name("runtimePercentile"), SQLDataType.REAL, this, "");

    /**
     * The column <code>leetcode_submission.memoryPercentile</code>.
     */
    public final TableField<LeetcodeSubmissionRecord, Float> MEMORYPERCENTILE = createField(DSL.name("memoryPercentile"), SQLDataType.REAL, this, "");

    /**
     * The column <code>leetcode_submission.lastTestcase</code>.
     */
    public final TableField<LeetcodeSubmissionRecord, String> LASTTESTCASE = createField(DSL.name("lastTestcase"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>leetcode_submission.inputFormatted</code>.
     */
    public final TableField<LeetcodeSubmissionRecord, String> INPUTFORMATTED = createField(DSL.name("inputFormatted"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>leetcode_submission.expectedOutput</code>.
     */
    public final TableField<LeetcodeSubmissionRecord, String> EXPECTEDOUTPUT = createField(DSL.name("expectedOutput"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>leetcode_submission.codeOutput</code>.
     */
    public final TableField<LeetcodeSubmissionRecord, String> CODEOUTPUT = createField(DSL.name("codeOutput"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>leetcode_submission.stdOutput</code>.
     */
    public final TableField<LeetcodeSubmissionRecord, String> STDOUTPUT = createField(DSL.name("stdOutput"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>leetcode_submission.statusRuntime</code>.
     */
    public final TableField<LeetcodeSubmissionRecord, String> STATUSRUNTIME = createField(DSL.name("statusRuntime"), SQLDataType.CLOB, this, "");

    private LeetcodeSubmission(Name alias, Table<LeetcodeSubmissionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private LeetcodeSubmission(Name alias, Table<LeetcodeSubmissionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>leetcode_submission</code> table reference
     */
    public LeetcodeSubmission(String alias) {
        this(DSL.name(alias), LEETCODE_SUBMISSION);
    }

    /**
     * Create an aliased <code>leetcode_submission</code> table reference
     */
    public LeetcodeSubmission(Name alias) {
        this(alias, LEETCODE_SUBMISSION);
    }

    /**
     * Create a <code>leetcode_submission</code> table reference
     */
    public LeetcodeSubmission() {
        this(DSL.name("leetcode_submission"), null);
    }

    public <O extends Record> LeetcodeSubmission(Table<O> path, ForeignKey<O, LeetcodeSubmissionRecord> childPath, InverseForeignKey<O, LeetcodeSubmissionRecord> parentPath) {
        super(path, childPath, parentPath, LEETCODE_SUBMISSION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class LeetcodeSubmissionPath extends LeetcodeSubmission implements Path<LeetcodeSubmissionRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> LeetcodeSubmissionPath(Table<O> path, ForeignKey<O, LeetcodeSubmissionRecord> childPath, InverseForeignKey<O, LeetcodeSubmissionRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private LeetcodeSubmissionPath(Name alias, Table<LeetcodeSubmissionRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public LeetcodeSubmissionPath as(String alias) {
            return new LeetcodeSubmissionPath(DSL.name(alias), this);
        }

        @Override
        public LeetcodeSubmissionPath as(Name alias) {
            return new LeetcodeSubmissionPath(alias, this);
        }

        @Override
        public LeetcodeSubmissionPath as(Table<?> alias) {
            return new LeetcodeSubmissionPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<LeetcodeSubmissionRecord> getPrimaryKey() {
        return Keys.LEETCODE_SUBMISSION__PK_LEETCODE_SUBMISSION;
    }

    @Override
    public List<ForeignKey<LeetcodeSubmissionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.LEETCODE_SUBMISSION__FK_LEETCODE_SUBMISSION_PK_SOLUTION_SUBMISSION);
    }

    private transient SolutionSubmissionPath _solutionSubmission;

    /**
     * Get the implicit join path to the <code>solution_submission</code> table.
     */
    public SolutionSubmissionPath solutionSubmission() {
        if (_solutionSubmission == null)
            _solutionSubmission = new SolutionSubmissionPath(this, Keys.LEETCODE_SUBMISSION__FK_LEETCODE_SUBMISSION_PK_SOLUTION_SUBMISSION, null);

        return _solutionSubmission;
    }

    @Override
    public LeetcodeSubmission as(String alias) {
        return new LeetcodeSubmission(DSL.name(alias), this);
    }

    @Override
    public LeetcodeSubmission as(Name alias) {
        return new LeetcodeSubmission(alias, this);
    }

    @Override
    public LeetcodeSubmission as(Table<?> alias) {
        return new LeetcodeSubmission(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public LeetcodeSubmission rename(String name) {
        return new LeetcodeSubmission(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LeetcodeSubmission rename(Name name) {
        return new LeetcodeSubmission(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public LeetcodeSubmission rename(Table<?> name) {
        return new LeetcodeSubmission(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LeetcodeSubmission where(Condition condition) {
        return new LeetcodeSubmission(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LeetcodeSubmission where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LeetcodeSubmission where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LeetcodeSubmission where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LeetcodeSubmission where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LeetcodeSubmission where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LeetcodeSubmission where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LeetcodeSubmission where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LeetcodeSubmission whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LeetcodeSubmission whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
