/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables;


import com.wenjunhuang.codeepiphany.database.DefaultSchema;
import com.wenjunhuang.codeepiphany.database.Keys;
import com.wenjunhuang.codeepiphany.database.tables.Challenge.ChallengePath;
import com.wenjunhuang.codeepiphany.database.tables.records.LeetcodeChallengeRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LeetcodeChallenge extends TableImpl<LeetcodeChallengeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>leetcode_challenge</code>
     */
    public static final LeetcodeChallenge LEETCODE_CHALLENGE = new LeetcodeChallenge();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LeetcodeChallengeRecord> getRecordType() {
        return LeetcodeChallengeRecord.class;
    }

    /**
     * The column <code>leetcode_challenge.frontendQuestionId</code>.
     */
    public final TableField<LeetcodeChallengeRecord, String> FRONTENDQUESTIONID = createField(DSL.name("frontendQuestionId"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>leetcode_challenge.testCase</code>.
     */
    public final TableField<LeetcodeChallengeRecord, String> TESTCASE = createField(DSL.name("testCase"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>leetcode_challenge.id</code>.
     */
    public final TableField<LeetcodeChallengeRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    private LeetcodeChallenge(Name alias, Table<LeetcodeChallengeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private LeetcodeChallenge(Name alias, Table<LeetcodeChallengeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>leetcode_challenge</code> table reference
     */
    public LeetcodeChallenge(String alias) {
        this(DSL.name(alias), LEETCODE_CHALLENGE);
    }

    /**
     * Create an aliased <code>leetcode_challenge</code> table reference
     */
    public LeetcodeChallenge(Name alias) {
        this(alias, LEETCODE_CHALLENGE);
    }

    /**
     * Create a <code>leetcode_challenge</code> table reference
     */
    public LeetcodeChallenge() {
        this(DSL.name("leetcode_challenge"), null);
    }

    public <O extends Record> LeetcodeChallenge(Table<O> path, ForeignKey<O, LeetcodeChallengeRecord> childPath, InverseForeignKey<O, LeetcodeChallengeRecord> parentPath) {
        super(path, childPath, parentPath, LEETCODE_CHALLENGE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class LeetcodeChallengePath extends LeetcodeChallenge implements Path<LeetcodeChallengeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> LeetcodeChallengePath(Table<O> path, ForeignKey<O, LeetcodeChallengeRecord> childPath, InverseForeignKey<O, LeetcodeChallengeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private LeetcodeChallengePath(Name alias, Table<LeetcodeChallengeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public LeetcodeChallengePath as(String alias) {
            return new LeetcodeChallengePath(DSL.name(alias), this);
        }

        @Override
        public LeetcodeChallengePath as(Name alias) {
            return new LeetcodeChallengePath(alias, this);
        }

        @Override
        public LeetcodeChallengePath as(Table<?> alias) {
            return new LeetcodeChallengePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<LeetcodeChallengeRecord> getPrimaryKey() {
        return Keys.LEETCODE_CHALLENGE__PK_LEETCODE_CHALLENGE;
    }

    @Override
    public List<ForeignKey<LeetcodeChallengeRecord, ?>> getReferences() {
        return Arrays.asList(Keys.LEETCODE_CHALLENGE__FK_LEETCODE_CHALLENGE_PK_CHALLENGE);
    }

    private transient ChallengePath _challenge;

    /**
     * Get the implicit join path to the <code>challenge</code> table.
     */
    public ChallengePath challenge() {
        if (_challenge == null)
            _challenge = new ChallengePath(this, Keys.LEETCODE_CHALLENGE__FK_LEETCODE_CHALLENGE_PK_CHALLENGE, null);

        return _challenge;
    }

    @Override
    public LeetcodeChallenge as(String alias) {
        return new LeetcodeChallenge(DSL.name(alias), this);
    }

    @Override
    public LeetcodeChallenge as(Name alias) {
        return new LeetcodeChallenge(alias, this);
    }

    @Override
    public LeetcodeChallenge as(Table<?> alias) {
        return new LeetcodeChallenge(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public LeetcodeChallenge rename(String name) {
        return new LeetcodeChallenge(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LeetcodeChallenge rename(Name name) {
        return new LeetcodeChallenge(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public LeetcodeChallenge rename(Table<?> name) {
        return new LeetcodeChallenge(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LeetcodeChallenge where(Condition condition) {
        return new LeetcodeChallenge(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LeetcodeChallenge where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LeetcodeChallenge where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LeetcodeChallenge where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LeetcodeChallenge where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LeetcodeChallenge where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LeetcodeChallenge where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LeetcodeChallenge where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LeetcodeChallenge whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LeetcodeChallenge whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
