/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables;


import com.wenjunhuang.codeepiphany.database.DefaultSchema;
import com.wenjunhuang.codeepiphany.database.Indexes;
import com.wenjunhuang.codeepiphany.database.Keys;
import com.wenjunhuang.codeepiphany.database.tables.Challenge.ChallengePath;
import com.wenjunhuang.codeepiphany.database.tables.ChallengeLanguage.ChallengeLanguagePath;
import com.wenjunhuang.codeepiphany.database.tables.SolutionSubmission.SolutionSubmissionPath;
import com.wenjunhuang.codeepiphany.database.tables.records.SolutionRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Solution extends TableImpl<SolutionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>solution</code>
     */
    public static final Solution SOLUTION = new Solution();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SolutionRecord> getRecordType() {
        return SolutionRecord.class;
    }

    /**
     * The column <code>solution.id</code>.
     */
    public final TableField<SolutionRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>solution.challengeId</code>.
     */
    public final TableField<SolutionRecord, Integer> CHALLENGEID = createField(DSL.name("challengeId"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>solution.challengeLanguageId</code>.
     */
    public final TableField<SolutionRecord, Integer> CHALLENGELANGUAGEID = createField(DSL.name("challengeLanguageId"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>solution.createDateTime</code>.
     */
    public final TableField<SolutionRecord, Integer> CREATEDATETIME = createField(DSL.name("createDateTime"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>solution.tags</code>.
     */
    public final TableField<SolutionRecord, String> TAGS = createField(DSL.name("tags"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>solution.remark</code>.
     */
    public final TableField<SolutionRecord, String> REMARK = createField(DSL.name("remark"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>solution.title</code>.
     */
    public final TableField<SolutionRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>solution.isDefault</code>.
     */
    public final TableField<SolutionRecord, Integer> ISDEFAULT = createField(DSL.name("isDefault"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    private Solution(Name alias, Table<SolutionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Solution(Name alias, Table<SolutionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>solution</code> table reference
     */
    public Solution(String alias) {
        this(DSL.name(alias), SOLUTION);
    }

    /**
     * Create an aliased <code>solution</code> table reference
     */
    public Solution(Name alias) {
        this(alias, SOLUTION);
    }

    /**
     * Create a <code>solution</code> table reference
     */
    public Solution() {
        this(DSL.name("solution"), null);
    }

    public <O extends Record> Solution(Table<O> path, ForeignKey<O, SolutionRecord> childPath, InverseForeignKey<O, SolutionRecord> parentPath) {
        super(path, childPath, parentPath, SOLUTION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SolutionPath extends Solution implements Path<SolutionRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SolutionPath(Table<O> path, ForeignKey<O, SolutionRecord> childPath, InverseForeignKey<O, SolutionRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SolutionPath(Name alias, Table<SolutionRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SolutionPath as(String alias) {
            return new SolutionPath(DSL.name(alias), this);
        }

        @Override
        public SolutionPath as(Name alias) {
            return new SolutionPath(alias, this);
        }

        @Override
        public SolutionPath as(Table<?> alias) {
            return new SolutionPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SOLUTION_CHALLENGELANGUAGEID_TITLE_UINDEX);
    }

    @Override
    public Identity<SolutionRecord, Integer> getIdentity() {
        return (Identity<SolutionRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<SolutionRecord> getPrimaryKey() {
        return Keys.SOLUTION__PK_SOLUTION;
    }

    @Override
    public List<ForeignKey<SolutionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SOLUTION__FK_SOLUTION_PK_CHALLENGE, Keys.SOLUTION__FK_SOLUTION_PK_CHALLENGE_LANGUAGE);
    }

    private transient ChallengePath _challenge;

    /**
     * Get the implicit join path to the <code>challenge</code> table.
     */
    public ChallengePath challenge() {
        if (_challenge == null)
            _challenge = new ChallengePath(this, Keys.SOLUTION__FK_SOLUTION_PK_CHALLENGE, null);

        return _challenge;
    }

    private transient ChallengeLanguagePath _challengeLanguage;

    /**
     * Get the implicit join path to the <code>challenge_language</code> table.
     */
    public ChallengeLanguagePath challengeLanguage() {
        if (_challengeLanguage == null)
            _challengeLanguage = new ChallengeLanguagePath(this, Keys.SOLUTION__FK_SOLUTION_PK_CHALLENGE_LANGUAGE, null);

        return _challengeLanguage;
    }

    private transient SolutionSubmissionPath _solutionSubmission;

    /**
     * Get the implicit to-many join path to the
     * <code>solution_submission</code> table
     */
    public SolutionSubmissionPath solutionSubmission() {
        if (_solutionSubmission == null)
            _solutionSubmission = new SolutionSubmissionPath(this, null, Keys.SOLUTION_SUBMISSION__FK_SOLUTION_SUBMISSION_PK_SOLUTION.getInverseKey());

        return _solutionSubmission;
    }

    @Override
    public Solution as(String alias) {
        return new Solution(DSL.name(alias), this);
    }

    @Override
    public Solution as(Name alias) {
        return new Solution(alias, this);
    }

    @Override
    public Solution as(Table<?> alias) {
        return new Solution(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Solution rename(String name) {
        return new Solution(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Solution rename(Name name) {
        return new Solution(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Solution rename(Table<?> name) {
        return new Solution(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Solution where(Condition condition) {
        return new Solution(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Solution where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Solution where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Solution where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Solution where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Solution where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Solution where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Solution where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Solution whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Solution whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
