/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables;


import com.wenjunhuang.codeepiphany.database.DefaultSchema;
import com.wenjunhuang.codeepiphany.database.Keys;
import com.wenjunhuang.codeepiphany.database.tables.HackerrankSolutionSubmissionResult.HackerrankSolutionSubmissionResultPath;
import com.wenjunhuang.codeepiphany.database.tables.Solution.SolutionPath;
import com.wenjunhuang.codeepiphany.database.tables.records.SolutionSubmissionRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SolutionSubmission extends TableImpl<SolutionSubmissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>solution_submission</code>
     */
    public static final SolutionSubmission SOLUTION_SUBMISSION = new SolutionSubmission();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SolutionSubmissionRecord> getRecordType() {
        return SolutionSubmissionRecord.class;
    }

    /**
     * The column <code>solution_submission.id</code>.
     */
    public final TableField<SolutionSubmissionRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>solution_submission.dojoSubmissionId</code>.
     */
    public final TableField<SolutionSubmissionRecord, String> DOJOSUBMISSIONID = createField(DSL.name("dojoSubmissionId"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>solution_submission.submitDateTime</code>.
     */
    public final TableField<SolutionSubmissionRecord, Integer> SUBMITDATETIME = createField(DSL.name("submitDateTime"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>solution_submission.localCode</code>.
     */
    public final TableField<SolutionSubmissionRecord, String> LOCALCODE = createField(DSL.name("localCode"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>solution_submission.submitCode</code>.
     */
    public final TableField<SolutionSubmissionRecord, String> SUBMITCODE = createField(DSL.name("submitCode"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>solution_submission.state</code>.
     */
    public final TableField<SolutionSubmissionRecord, String> STATE = createField(DSL.name("state"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>solution_submission.solutionId</code>.
     */
    public final TableField<SolutionSubmissionRecord, Integer> SOLUTIONID = createField(DSL.name("solutionId"), SQLDataType.INTEGER.nullable(false), this, "");

    private SolutionSubmission(Name alias, Table<SolutionSubmissionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SolutionSubmission(Name alias, Table<SolutionSubmissionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>solution_submission</code> table reference
     */
    public SolutionSubmission(String alias) {
        this(DSL.name(alias), SOLUTION_SUBMISSION);
    }

    /**
     * Create an aliased <code>solution_submission</code> table reference
     */
    public SolutionSubmission(Name alias) {
        this(alias, SOLUTION_SUBMISSION);
    }

    /**
     * Create a <code>solution_submission</code> table reference
     */
    public SolutionSubmission() {
        this(DSL.name("solution_submission"), null);
    }

    public <O extends Record> SolutionSubmission(Table<O> path, ForeignKey<O, SolutionSubmissionRecord> childPath, InverseForeignKey<O, SolutionSubmissionRecord> parentPath) {
        super(path, childPath, parentPath, SOLUTION_SUBMISSION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SolutionSubmissionPath extends SolutionSubmission implements Path<SolutionSubmissionRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SolutionSubmissionPath(Table<O> path, ForeignKey<O, SolutionSubmissionRecord> childPath, InverseForeignKey<O, SolutionSubmissionRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SolutionSubmissionPath(Name alias, Table<SolutionSubmissionRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SolutionSubmissionPath as(String alias) {
            return new SolutionSubmissionPath(DSL.name(alias), this);
        }

        @Override
        public SolutionSubmissionPath as(Name alias) {
            return new SolutionSubmissionPath(alias, this);
        }

        @Override
        public SolutionSubmissionPath as(Table<?> alias) {
            return new SolutionSubmissionPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<SolutionSubmissionRecord, Integer> getIdentity() {
        return (Identity<SolutionSubmissionRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<SolutionSubmissionRecord> getPrimaryKey() {
        return Keys.SOLUTION_SUBMISSION__PK_SOLUTION_SUBMISSION;
    }

    @Override
    public List<ForeignKey<SolutionSubmissionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SOLUTION_SUBMISSION__FK_SOLUTION_SUBMISSION_PK_SOLUTION);
    }

    private transient SolutionPath _solution;

    /**
     * Get the implicit join path to the <code>solution</code> table.
     */
    public SolutionPath solution() {
        if (_solution == null)
            _solution = new SolutionPath(this, Keys.SOLUTION_SUBMISSION__FK_SOLUTION_SUBMISSION_PK_SOLUTION, null);

        return _solution;
    }

    private transient HackerrankSolutionSubmissionResultPath _hackerrankSolutionSubmissionResult;

    /**
     * Get the implicit to-many join path to the
     * <code>hackerrank_solution_submission_result</code> table
     */
    public HackerrankSolutionSubmissionResultPath hackerrankSolutionSubmissionResult() {
        if (_hackerrankSolutionSubmissionResult == null)
            _hackerrankSolutionSubmissionResult = new HackerrankSolutionSubmissionResultPath(this, null, Keys.HACKERRANK_SOLUTION_SUBMISSION_RESULT__FK_HACKERRANK_SOLUTION_SUBMISSION_RESULT_PK_SOLUTION_SUBMISSION.getInverseKey());

        return _hackerrankSolutionSubmissionResult;
    }

    @Override
    public SolutionSubmission as(String alias) {
        return new SolutionSubmission(DSL.name(alias), this);
    }

    @Override
    public SolutionSubmission as(Name alias) {
        return new SolutionSubmission(alias, this);
    }

    @Override
    public SolutionSubmission as(Table<?> alias) {
        return new SolutionSubmission(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SolutionSubmission rename(String name) {
        return new SolutionSubmission(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SolutionSubmission rename(Name name) {
        return new SolutionSubmission(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SolutionSubmission rename(Table<?> name) {
        return new SolutionSubmission(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SolutionSubmission where(Condition condition) {
        return new SolutionSubmission(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SolutionSubmission where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SolutionSubmission where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SolutionSubmission where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SolutionSubmission where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SolutionSubmission where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SolutionSubmission where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SolutionSubmission where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SolutionSubmission whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SolutionSubmission whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
