/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables.records;


import com.wenjunhuang.codeepiphany.database.tables.AtcoderChallenge;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AtcoderChallengeRecord extends UpdatableRecordImpl<AtcoderChallengeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>atcoder_challenge.id</code>.
     */
    public AtcoderChallengeRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>atcoder_challenge.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>atcoder_challenge.difficulty</code>.
     */
    public AtcoderChallengeRecord setDifficulty(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>atcoder_challenge.difficulty</code>.
     */
    public Integer getDifficulty() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>atcoder_challenge.contestId</code>.
     */
    public AtcoderChallengeRecord setContestid(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>atcoder_challenge.contestId</code>.
     */
    public String getContestid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>atcoder_challenge.problemIndex</code>.
     */
    public AtcoderChallengeRecord setProblemindex(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>atcoder_challenge.problemIndex</code>.
     */
    public String getProblemindex() {
        return (String) get(3);
    }

    /**
     * Setter for <code>atcoder_challenge.title</code>.
     */
    public AtcoderChallengeRecord setTitle(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>atcoder_challenge.title</code>.
     */
    public String getTitle() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AtcoderChallengeRecord
     */
    public AtcoderChallengeRecord() {
        super(AtcoderChallenge.ATCODER_CHALLENGE);
    }

    /**
     * Create a detached, initialised AtcoderChallengeRecord
     */
    public AtcoderChallengeRecord(Long id, Integer difficulty, String contestid, String problemindex, String title) {
        super(AtcoderChallenge.ATCODER_CHALLENGE);

        setId(id);
        setDifficulty(difficulty);
        setContestid(contestid);
        setProblemindex(problemindex);
        setTitle(title);
        resetChangedOnNotNull();
    }
}
