/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables.records;


import com.wenjunhuang.codeepiphany.database.tables.AtcoderProblems;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AtcoderProblemsRecord extends UpdatableRecordImpl<AtcoderProblemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>atcoder_problems.problemId</code>.
     */
    public AtcoderProblemsRecord setProblemid(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>atcoder_problems.problemId</code>.
     */
    public String getProblemid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>atcoder_problems.contestId</code>.
     */
    public AtcoderProblemsRecord setContestid(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>atcoder_problems.contestId</code>.
     */
    public String getContestid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>atcoder_problems.problemIndex</code>.
     */
    public AtcoderProblemsRecord setProblemindex(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>atcoder_problems.problemIndex</code>.
     */
    public String getProblemindex() {
        return (String) get(2);
    }

    /**
     * Setter for <code>atcoder_problems.name</code>.
     */
    public AtcoderProblemsRecord setName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>atcoder_problems.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>atcoder_problems.title</code>.
     */
    public AtcoderProblemsRecord setTitle(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>atcoder_problems.title</code>.
     */
    public String getTitle() {
        return (String) get(4);
    }

    /**
     * Setter for <code>atcoder_problems.shortestSubmissionId</code>.
     */
    public AtcoderProblemsRecord setShortestsubmissionid(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>atcoder_problems.shortestSubmissionId</code>.
     */
    public Long getShortestsubmissionid() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>atcoder_problems.shortestContestId</code>.
     */
    public AtcoderProblemsRecord setShortestcontestid(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>atcoder_problems.shortestContestId</code>.
     */
    public String getShortestcontestid() {
        return (String) get(6);
    }

    /**
     * Setter for <code>atcoder_problems.shortestUserId</code>.
     */
    public AtcoderProblemsRecord setShortestuserid(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>atcoder_problems.shortestUserId</code>.
     */
    public String getShortestuserid() {
        return (String) get(7);
    }

    /**
     * Setter for <code>atcoder_problems.fastestSubmissionId</code>.
     */
    public AtcoderProblemsRecord setFastestsubmissionid(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>atcoder_problems.fastestSubmissionId</code>.
     */
    public Long getFastestsubmissionid() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>atcoder_problems.fastestContestId</code>.
     */
    public AtcoderProblemsRecord setFastestcontestid(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>atcoder_problems.fastestContestId</code>.
     */
    public String getFastestcontestid() {
        return (String) get(9);
    }

    /**
     * Setter for <code>atcoder_problems.fastestUserId</code>.
     */
    public AtcoderProblemsRecord setFastestuserid(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>atcoder_problems.fastestUserId</code>.
     */
    public String getFastestuserid() {
        return (String) get(10);
    }

    /**
     * Setter for <code>atcoder_problems.firstSubmissionId</code>.
     */
    public AtcoderProblemsRecord setFirstsubmissionid(Long value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>atcoder_problems.firstSubmissionId</code>.
     */
    public Long getFirstsubmissionid() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>atcoder_problems.firstContestId</code>.
     */
    public AtcoderProblemsRecord setFirstcontestid(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>atcoder_problems.firstContestId</code>.
     */
    public String getFirstcontestid() {
        return (String) get(12);
    }

    /**
     * Setter for <code>atcoder_problems.firstUserId</code>.
     */
    public AtcoderProblemsRecord setFirstuserid(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>atcoder_problems.firstUserId</code>.
     */
    public String getFirstuserid() {
        return (String) get(13);
    }

    /**
     * Setter for <code>atcoder_problems.solverCount</code>.
     */
    public AtcoderProblemsRecord setSolvercount(Integer value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>atcoder_problems.solverCount</code>.
     */
    public Integer getSolvercount() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>atcoder_problems.id</code>.
     */
    public AtcoderProblemsRecord setId(Long value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>atcoder_problems.id</code>.
     */
    public Long getId() {
        return (Long) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AtcoderProblemsRecord
     */
    public AtcoderProblemsRecord() {
        super(AtcoderProblems.ATCODER_PROBLEMS);
    }

    /**
     * Create a detached, initialised AtcoderProblemsRecord
     */
    public AtcoderProblemsRecord(String problemid, String contestid, String problemindex, String name, String title, Long shortestsubmissionid, String shortestcontestid, String shortestuserid, Long fastestsubmissionid, String fastestcontestid, String fastestuserid, Long firstsubmissionid, String firstcontestid, String firstuserid, Integer solvercount, Long id) {
        super(AtcoderProblems.ATCODER_PROBLEMS);

        setProblemid(problemid);
        setContestid(contestid);
        setProblemindex(problemindex);
        setName(name);
        setTitle(title);
        setShortestsubmissionid(shortestsubmissionid);
        setShortestcontestid(shortestcontestid);
        setShortestuserid(shortestuserid);
        setFastestsubmissionid(fastestsubmissionid);
        setFastestcontestid(fastestcontestid);
        setFastestuserid(fastestuserid);
        setFirstsubmissionid(firstsubmissionid);
        setFirstcontestid(firstcontestid);
        setFirstuserid(firstuserid);
        setSolvercount(solvercount);
        setId(id);
        resetChangedOnNotNull();
    }
}
