/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables.records;


import com.wenjunhuang.codeepiphany.database.tables.AtcoderContests;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AtcoderContestsRecord extends UpdatableRecordImpl<AtcoderContestsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>atcoder_contests.contestId</code>.
     */
    public AtcoderContestsRecord setContestid(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>atcoder_contests.contestId</code>.
     */
    public String getContestid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>atcoder_contests.startEpochSecond</code>.
     */
    public AtcoderContestsRecord setStartepochsecond(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>atcoder_contests.startEpochSecond</code>.
     */
    public Integer getStartepochsecond() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>atcoder_contests.durationSecond</code>.
     */
    public AtcoderContestsRecord setDurationsecond(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>atcoder_contests.durationSecond</code>.
     */
    public Integer getDurationsecond() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>atcoder_contests.title</code>.
     */
    public AtcoderContestsRecord setTitle(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>atcoder_contests.title</code>.
     */
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>atcoder_contests.rateChange</code>.
     */
    public AtcoderContestsRecord setRatechange(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>atcoder_contests.rateChange</code>.
     */
    public String getRatechange() {
        return (String) get(4);
    }

    /**
     * Setter for <code>atcoder_contests.id</code>.
     */
    public AtcoderContestsRecord setId(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>atcoder_contests.id</code>.
     */
    public Long getId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AtcoderContestsRecord
     */
    public AtcoderContestsRecord() {
        super(AtcoderContests.ATCODER_CONTESTS);
    }

    /**
     * Create a detached, initialised AtcoderContestsRecord
     */
    public AtcoderContestsRecord(String contestid, Integer startepochsecond, Integer durationsecond, String title, String ratechange, Long id) {
        super(AtcoderContests.ATCODER_CONTESTS);

        setContestid(contestid);
        setStartepochsecond(startepochsecond);
        setDurationsecond(durationsecond);
        setTitle(title);
        setRatechange(ratechange);
        setId(id);
        resetChangedOnNotNull();
    }
}
