/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables.records;


import com.wenjunhuang.codeepiphany.database.tables.ChallengeLanguage;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChallengeLanguageRecord extends UpdatableRecordImpl<ChallengeLanguageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>challenge_language.challengeId</code>.
     */
    public ChallengeLanguageRecord setChallengeid(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>challenge_language.challengeId</code>.
     */
    public Long getChallengeid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>challenge_language.language</code>.
     */
    public ChallengeLanguageRecord setLanguage(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>challenge_language.language</code>.
     */
    public String getLanguage() {
        return (String) get(1);
    }

    /**
     * Setter for <code>challenge_language.codeTemplate</code>.
     */
    public ChallengeLanguageRecord setCodetemplate(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>challenge_language.codeTemplate</code>.
     */
    public String getCodetemplate() {
        return (String) get(2);
    }

    /**
     * Setter for <code>challenge_language.id</code>.
     */
    public ChallengeLanguageRecord setId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>challenge_language.id</code>.
     */
    public Long getId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>challenge_language.languageVersion</code>.
     */
    public ChallengeLanguageRecord setLanguageversion(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>challenge_language.languageVersion</code>.
     */
    public String getLanguageversion() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChallengeLanguageRecord
     */
    public ChallengeLanguageRecord() {
        super(ChallengeLanguage.CHALLENGE_LANGUAGE);
    }

    /**
     * Create a detached, initialised ChallengeLanguageRecord
     */
    public ChallengeLanguageRecord(Long challengeid, String language, String codetemplate, Long id, String languageversion) {
        super(ChallengeLanguage.CHALLENGE_LANGUAGE);

        setChallengeid(challengeid);
        setLanguage(language);
        setCodetemplate(codetemplate);
        setId(id);
        setLanguageversion(languageversion);
        resetChangedOnNotNull();
    }
}
