/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables.records;


import com.wenjunhuang.codeepiphany.database.tables.Challenge;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChallengeRecord extends UpdatableRecordImpl<ChallengeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>challenge.id</code>.
     */
    public ChallengeRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>challenge.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>challenge.title</code>.
     */
    public ChallengeRecord setTitle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>challenge.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>challenge.slug</code>.
     */
    public ChallengeRecord setSlug(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>challenge.slug</code>.
     */
    public String getSlug() {
        return (String) get(2);
    }

    /**
     * Setter for <code>challenge.dojo</code>.
     */
    public ChallengeRecord setDojo(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>challenge.dojo</code>.
     */
    public String getDojo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>challenge.dojoId</code>.
     */
    public ChallengeRecord setDojoid(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>challenge.dojoId</code>.
     */
    public String getDojoid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>challenge.difficulty</code>.
     */
    public ChallengeRecord setDifficulty(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>challenge.difficulty</code>.
     */
    public String getDifficulty() {
        return (String) get(5);
    }

    /**
     * Setter for <code>challenge.description</code>.
     */
    public ChallengeRecord setDescription(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>challenge.description</code>.
     */
    public String getDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>challenge.tags</code>.
     */
    public ChallengeRecord setTags(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>challenge.tags</code>.
     */
    public String getTags() {
        return (String) get(7);
    }

    /**
     * Setter for <code>challenge.remark</code>.
     */
    public ChallengeRecord setRemark(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>challenge.remark</code>.
     */
    public String getRemark() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChallengeRecord
     */
    public ChallengeRecord() {
        super(Challenge.CHALLENGE);
    }

    /**
     * Create a detached, initialised ChallengeRecord
     */
    public ChallengeRecord(Long id, String title, String slug, String dojo, String dojoid, String difficulty, String description, String tags, String remark) {
        super(Challenge.CHALLENGE);

        setId(id);
        setTitle(title);
        setSlug(slug);
        setDojo(dojo);
        setDojoid(dojoid);
        setDifficulty(difficulty);
        setDescription(description);
        setTags(tags);
        setRemark(remark);
        resetChangedOnNotNull();
    }
}
