/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables.records;


import com.wenjunhuang.codeepiphany.database.tables.CodeforcesChallenge;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CodeforcesChallengeRecord extends UpdatableRecordImpl<CodeforcesChallengeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>codeforces_challenge.id</code>.
     */
    public CodeforcesChallengeRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>codeforces_challenge.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>codeforces_challenge.contestId</code>.
     */
    public CodeforcesChallengeRecord setContestid(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>codeforces_challenge.contestId</code>.
     */
    public Long getContestid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>codeforces_challenge.index</code>.
     */
    public CodeforcesChallengeRecord setIndex(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>codeforces_challenge.index</code>.
     */
    public String getIndex() {
        return (String) get(2);
    }

    /**
     * Setter for <code>codeforces_challenge.problemsetName</code>.
     */
    public CodeforcesChallengeRecord setProblemsetname(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>codeforces_challenge.problemsetName</code>.
     */
    public String getProblemsetname() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CodeforcesChallengeRecord
     */
    public CodeforcesChallengeRecord() {
        super(CodeforcesChallenge.CODEFORCES_CHALLENGE);
    }

    /**
     * Create a detached, initialised CodeforcesChallengeRecord
     */
    public CodeforcesChallengeRecord(Long id, Long contestid, String index, String problemsetname) {
        super(CodeforcesChallenge.CODEFORCES_CHALLENGE);

        setId(id);
        setContestid(contestid);
        setIndex(index);
        setProblemsetname(problemsetname);
        resetChangedOnNotNull();
    }
}
