/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables.records;


import com.wenjunhuang.codeepiphany.database.tables.CodeforcesProblemsets;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CodeforcesProblemsetsRecord extends UpdatableRecordImpl<CodeforcesProblemsetsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>codeforces_problemsets.contestId</code>.
     */
    public CodeforcesProblemsetsRecord setContestid(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>codeforces_problemsets.contestId</code>.
     */
    public Long getContestid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>codeforces_problemsets.index</code>.
     */
    public CodeforcesProblemsetsRecord setIndex(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>codeforces_problemsets.index</code>.
     */
    public String getIndex() {
        return (String) get(1);
    }

    /**
     * Setter for <code>codeforces_problemsets.name</code>.
     */
    public CodeforcesProblemsetsRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>codeforces_problemsets.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>codeforces_problemsets.type</code>.
     */
    public CodeforcesProblemsetsRecord setType(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>codeforces_problemsets.type</code>.
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>codeforces_problemsets.points</code>.
     */
    public CodeforcesProblemsetsRecord setPoints(Float value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>codeforces_problemsets.points</code>.
     */
    public Float getPoints() {
        return (Float) get(4);
    }

    /**
     * Setter for <code>codeforces_problemsets.tags</code>.
     */
    public CodeforcesProblemsetsRecord setTags(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>codeforces_problemsets.tags</code>.
     */
    public String getTags() {
        return (String) get(5);
    }

    /**
     * Setter for <code>codeforces_problemsets.solvedCount</code>.
     */
    public CodeforcesProblemsetsRecord setSolvedcount(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>codeforces_problemsets.solvedCount</code>.
     */
    public Integer getSolvedcount() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>codeforces_problemsets.lastUpdateDateTime</code>.
     */
    public CodeforcesProblemsetsRecord setLastupdatedatetime(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>codeforces_problemsets.lastUpdateDateTime</code>.
     */
    public LocalDateTime getLastupdatedatetime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>codeforces_problemsets.id</code>.
     */
    public CodeforcesProblemsetsRecord setId(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>codeforces_problemsets.id</code>.
     */
    public Long getId() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CodeforcesProblemsetsRecord
     */
    public CodeforcesProblemsetsRecord() {
        super(CodeforcesProblemsets.CODEFORCES_PROBLEMSETS);
    }

    /**
     * Create a detached, initialised CodeforcesProblemsetsRecord
     */
    public CodeforcesProblemsetsRecord(Long contestid, String index, String name, String type, Float points, String tags, Integer solvedcount, LocalDateTime lastupdatedatetime, Long id) {
        super(CodeforcesProblemsets.CODEFORCES_PROBLEMSETS);

        setContestid(contestid);
        setIndex(index);
        setName(name);
        setType(type);
        setPoints(points);
        setTags(tags);
        setSolvedcount(solvedcount);
        setLastupdatedatetime(lastupdatedatetime);
        setId(id);
        resetChangedOnNotNull();
    }
}
