/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables.records;


import com.wenjunhuang.codeepiphany.database.tables.CodeforcesTagsFts;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CodeforcesTagsFtsRecord extends TableRecordImpl<CodeforcesTagsFtsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public CodeforcesTagsFtsRecord setTags(Object value) {
        set(0, value);
        return this;
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getTags() {
        return get(0);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CodeforcesTagsFtsRecord
     */
    public CodeforcesTagsFtsRecord() {
        super(CodeforcesTagsFts.CODEFORCES_TAGS_FTS);
    }

    /**
     * Create a detached, initialised CodeforcesTagsFtsRecord
     */
    public CodeforcesTagsFtsRecord(Object tags) {
        super(CodeforcesTagsFts.CODEFORCES_TAGS_FTS);

        setTags(tags);
        resetChangedOnNotNull();
    }
}
