/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables.records;


import com.wenjunhuang.codeepiphany.database.tables.HackerrankSubmissionCase;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HackerrankSubmissionCaseRecord extends UpdatableRecordImpl<HackerrankSubmissionCaseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>hackerrank_submission_case.id</code>.
     */
    public HackerrankSubmissionCaseRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_submission_case.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>hackerrank_submission_case.state</code>.
     */
    public HackerrankSubmissionCaseRecord setState(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_submission_case.state</code>.
     */
    public String getState() {
        return (String) get(1);
    }

    /**
     * Setter for <code>hackerrank_submission_case.message</code>.
     */
    public HackerrankSubmissionCaseRecord setMessage(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_submission_case.message</code>.
     */
    public String getMessage() {
        return (String) get(2);
    }

    /**
     * Setter for <code>hackerrank_submission_case.num</code>.
     */
    public HackerrankSubmissionCaseRecord setNum(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_submission_case.num</code>.
     */
    public Integer getNum() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>hackerrank_submission_case.stdIn</code>.
     */
    public HackerrankSubmissionCaseRecord setStdin(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_submission_case.stdIn</code>.
     */
    public String getStdin() {
        return (String) get(4);
    }

    /**
     * Setter for <code>hackerrank_submission_case.expectedOutput</code>.
     */
    public HackerrankSubmissionCaseRecord setExpectedoutput(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_submission_case.expectedOutput</code>.
     */
    public String getExpectedoutput() {
        return (String) get(5);
    }

    /**
     * Setter for <code>hackerrank_submission_case.submissionId</code>.
     */
    public HackerrankSubmissionCaseRecord setSubmissionid(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_submission_case.submissionId</code>.
     */
    public Integer getSubmissionid() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HackerrankSubmissionCaseRecord
     */
    public HackerrankSubmissionCaseRecord() {
        super(HackerrankSubmissionCase.HACKERRANK_SUBMISSION_CASE);
    }

    /**
     * Create a detached, initialised HackerrankSubmissionCaseRecord
     */
    public HackerrankSubmissionCaseRecord(Integer id, String state, String message, Integer num, String stdin, String expectedoutput, Integer submissionid) {
        super(HackerrankSubmissionCase.HACKERRANK_SUBMISSION_CASE);

        setId(id);
        setState(state);
        setMessage(message);
        setNum(num);
        setStdin(stdin);
        setExpectedoutput(expectedoutput);
        setSubmissionid(submissionid);
        resetChangedOnNotNull();
    }
}
