/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables.records;


import com.wenjunhuang.codeepiphany.database.tables.HackerrankChallenge;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HackerrankChallengeRecord extends UpdatableRecordImpl<HackerrankChallengeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>hackerrank_challenge.id</code>.
     */
    public HackerrankChallengeRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_challenge.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>hackerrank_challenge.contestSlug</code>.
     */
    public HackerrankChallengeRecord setContestslug(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_challenge.contestSlug</code>.
     */
    public String getContestslug() {
        return (String) get(1);
    }

    /**
     * Setter for <code>hackerrank_challenge.contest</code>.
     */
    public HackerrankChallengeRecord setContest(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_challenge.contest</code>.
     */
    public String getContest() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HackerrankChallengeRecord
     */
    public HackerrankChallengeRecord() {
        super(HackerrankChallenge.HACKERRANK_CHALLENGE);
    }

    /**
     * Create a detached, initialised HackerrankChallengeRecord
     */
    public HackerrankChallengeRecord(Integer id, String contestslug, String contest) {
        super(HackerrankChallenge.HACKERRANK_CHALLENGE);

        setId(id);
        setContestslug(contestslug);
        setContest(contest);
        resetChangedOnNotNull();
    }
}
