/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables.records;


import com.wenjunhuang.codeepiphany.database.tables.HackerrankChallenge;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HackerrankChallengeRecord extends UpdatableRecordImpl<HackerrankChallengeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>hackerrank_challenge.challengeId</code>.
     */
    public HackerrankChallengeRecord setChallengeid(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_challenge.challengeId</code>.
     */
    public Integer getChallengeid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>hackerrank_challenge.contestSlug</code>.
     */
    public HackerrankChallengeRecord setContestslug(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_challenge.contestSlug</code>.
     */
    public String getContestslug() {
        return (String) get(1);
    }

    /**
     * Setter for <code>hackerrank_challenge.contest</code>.
     */
    public HackerrankChallengeRecord setContest(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_challenge.contest</code>.
     */
    public String getContest() {
        return (String) get(2);
    }

    /**
     * Setter for <code>hackerrank_challenge.codeHeader</code>.
     */
    public HackerrankChallengeRecord setCodeheader(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_challenge.codeHeader</code>.
     */
    public String getCodeheader() {
        return (String) get(3);
    }

    /**
     * Setter for <code>hackerrank_challenge.codeTemplate</code>.
     */
    public HackerrankChallengeRecord setCodetemplate(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_challenge.codeTemplate</code>.
     */
    public String getCodetemplate() {
        return (String) get(4);
    }

    /**
     * Setter for <code>hackerrank_challenge.codeTail</code>.
     */
    public HackerrankChallengeRecord setCodetail(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_challenge.codeTail</code>.
     */
    public String getCodetail() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HackerrankChallengeRecord
     */
    public HackerrankChallengeRecord() {
        super(HackerrankChallenge.HACKERRANK_CHALLENGE);
    }

    /**
     * Create a detached, initialised HackerrankChallengeRecord
     */
    public HackerrankChallengeRecord(Integer challengeid, String contestslug, String contest, String codeheader, String codetemplate, String codetail) {
        super(HackerrankChallenge.HACKERRANK_CHALLENGE);

        setChallengeid(challengeid);
        setContestslug(contestslug);
        setContest(contest);
        setCodeheader(codeheader);
        setCodetemplate(codetemplate);
        setCodetail(codetail);
        resetChangedOnNotNull();
    }
}
