/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables.records;


import com.wenjunhuang.codeepiphany.database.tables.HackerrankSolutionSubmissionResult;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HackerrankSolutionSubmissionResultRecord extends UpdatableRecordImpl<HackerrankSolutionSubmissionResultRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>hackerrank_solution_submission_result.id</code>.
     */
    public HackerrankSolutionSubmissionResultRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_solution_submission_result.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>hackerrank_solution_submission_result.state</code>.
     */
    public HackerrankSolutionSubmissionResultRecord setState(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_solution_submission_result.state</code>.
     */
    public String getState() {
        return (String) get(1);
    }

    /**
     * Setter for <code>hackerrank_solution_submission_result.message</code>.
     */
    public HackerrankSolutionSubmissionResultRecord setMessage(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_solution_submission_result.message</code>.
     */
    public String getMessage() {
        return (String) get(2);
    }

    /**
     * Setter for <code>hackerrank_solution_submission_result.num</code>.
     */
    public HackerrankSolutionSubmissionResultRecord setNum(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_solution_submission_result.num</code>.
     */
    public Integer getNum() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>hackerrank_solution_submission_result.stdIn</code>.
     */
    public HackerrankSolutionSubmissionResultRecord setStdin(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_solution_submission_result.stdIn</code>.
     */
    public String getStdin() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>hackerrank_solution_submission_result.expectedOutput</code>.
     */
    public HackerrankSolutionSubmissionResultRecord setExpectedoutput(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>hackerrank_solution_submission_result.expectedOutput</code>.
     */
    public String getExpectedoutput() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>hackerrank_solution_submission_result.submissionId</code>.
     */
    public HackerrankSolutionSubmissionResultRecord setSubmissionid(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for
     * <code>hackerrank_solution_submission_result.submissionId</code>.
     */
    public Integer getSubmissionid() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HackerrankSolutionSubmissionResultRecord
     */
    public HackerrankSolutionSubmissionResultRecord() {
        super(HackerrankSolutionSubmissionResult.HACKERRANK_SOLUTION_SUBMISSION_RESULT);
    }

    /**
     * Create a detached, initialised HackerrankSolutionSubmissionResultRecord
     */
    public HackerrankSolutionSubmissionResultRecord(Integer id, String state, String message, Integer num, String stdin, String expectedoutput, Integer submissionid) {
        super(HackerrankSolutionSubmissionResult.HACKERRANK_SOLUTION_SUBMISSION_RESULT);

        setId(id);
        setState(state);
        setMessage(message);
        setNum(num);
        setStdin(stdin);
        setExpectedoutput(expectedoutput);
        setSubmissionid(submissionid);
        resetChangedOnNotNull();
    }
}
