/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables.records;


import com.wenjunhuang.codeepiphany.database.tables.HackerrankChallengeLanguage;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HackerrankChallengeLanguageRecord extends UpdatableRecordImpl<HackerrankChallengeLanguageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>hackerrank_challenge_language.id</code>.
     */
    public HackerrankChallengeLanguageRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_challenge_language.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>hackerrank_challenge_language.codeHeader</code>.
     */
    public HackerrankChallengeLanguageRecord setCodeheader(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_challenge_language.codeHeader</code>.
     */
    public String getCodeheader() {
        return (String) get(1);
    }

    /**
     * Setter for <code>hackerrank_challenge_language.codeTemplate</code>.
     */
    public HackerrankChallengeLanguageRecord setCodetemplate(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_challenge_language.codeTemplate</code>.
     */
    public String getCodetemplate() {
        return (String) get(2);
    }

    /**
     * Setter for <code>hackerrank_challenge_language.codeTail</code>.
     */
    public HackerrankChallengeLanguageRecord setCodetail(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_challenge_language.codeTail</code>.
     */
    public String getCodetail() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HackerrankChallengeLanguageRecord
     */
    public HackerrankChallengeLanguageRecord() {
        super(HackerrankChallengeLanguage.HACKERRANK_CHALLENGE_LANGUAGE);
    }

    /**
     * Create a detached, initialised HackerrankChallengeLanguageRecord
     */
    public HackerrankChallengeLanguageRecord(Integer id, String codeheader, String codetemplate, String codetail) {
        super(HackerrankChallengeLanguage.HACKERRANK_CHALLENGE_LANGUAGE);

        setId(id);
        setCodeheader(codeheader);
        setCodetemplate(codetemplate);
        setCodetail(codetail);
        resetChangedOnNotNull();
    }
}
