/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables.records;


import com.wenjunhuang.codeepiphany.database.tables.HackerrankSubmissionCase;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HackerrankSubmissionCaseRecord extends UpdatableRecordImpl<HackerrankSubmissionCaseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>hackerrank_submission_case.id</code>.
     */
    public HackerrankSubmissionCaseRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_submission_case.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>hackerrank_submission_case.testcaseMessage</code>.
     */
    public HackerrankSubmissionCaseRecord setTestcasemessage(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_submission_case.testcaseMessage</code>.
     */
    public String getTestcasemessage() {
        return (String) get(1);
    }

    /**
     * Setter for <code>hackerrank_submission_case.num</code>.
     */
    public HackerrankSubmissionCaseRecord setNum(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_submission_case.num</code>.
     */
    public Integer getNum() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>hackerrank_submission_case.stdIn</code>.
     */
    public HackerrankSubmissionCaseRecord setStdin(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_submission_case.stdIn</code>.
     */
    public String getStdin() {
        return (String) get(3);
    }

    /**
     * Setter for <code>hackerrank_submission_case.expectedOutput</code>.
     */
    public HackerrankSubmissionCaseRecord setExpectedoutput(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_submission_case.expectedOutput</code>.
     */
    public String getExpectedoutput() {
        return (String) get(4);
    }

    /**
     * Setter for <code>hackerrank_submission_case.submissionId</code>.
     */
    public HackerrankSubmissionCaseRecord setSubmissionid(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_submission_case.submissionId</code>.
     */
    public Long getSubmissionid() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>hackerrank_submission_case.codecheckerSignal</code>.
     */
    public HackerrankSubmissionCaseRecord setCodecheckersignal(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_submission_case.codecheckerSignal</code>.
     */
    public Integer getCodecheckersignal() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>hackerrank_submission_case.codecheckerTime</code>.
     */
    public HackerrankSubmissionCaseRecord setCodecheckertime(Float value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_submission_case.codecheckerTime</code>.
     */
    public Float getCodecheckertime() {
        return (Float) get(7);
    }

    /**
     * Setter for <code>hackerrank_submission_case.testcaseStatus</code>.
     */
    public HackerrankSubmissionCaseRecord setTestcasestatus(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>hackerrank_submission_case.testcaseStatus</code>.
     */
    public Integer getTestcasestatus() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HackerrankSubmissionCaseRecord
     */
    public HackerrankSubmissionCaseRecord() {
        super(HackerrankSubmissionCase.HACKERRANK_SUBMISSION_CASE);
    }

    /**
     * Create a detached, initialised HackerrankSubmissionCaseRecord
     */
    public HackerrankSubmissionCaseRecord(Long id, String testcasemessage, Integer num, String stdin, String expectedoutput, Long submissionid, Integer codecheckersignal, Float codecheckertime, Integer testcasestatus) {
        super(HackerrankSubmissionCase.HACKERRANK_SUBMISSION_CASE);

        setId(id);
        setTestcasemessage(testcasemessage);
        setNum(num);
        setStdin(stdin);
        setExpectedoutput(expectedoutput);
        setSubmissionid(submissionid);
        setCodecheckersignal(codecheckersignal);
        setCodecheckertime(codecheckertime);
        setTestcasestatus(testcasestatus);
        resetChangedOnNotNull();
    }
}
