/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables.records;


import com.wenjunhuang.codeepiphany.database.tables.LeetcodeChallenge;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LeetcodeChallengeRecord extends UpdatableRecordImpl<LeetcodeChallengeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>leetcode_challenge.frontendQuestionId</code>.
     */
    public LeetcodeChallengeRecord setFrontendquestionid(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>leetcode_challenge.frontendQuestionId</code>.
     */
    public String getFrontendquestionid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>leetcode_challenge.testCase</code>.
     */
    public LeetcodeChallengeRecord setTestcase(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>leetcode_challenge.testCase</code>.
     */
    public String getTestcase() {
        return (String) get(1);
    }

    /**
     * Setter for <code>leetcode_challenge.id</code>.
     */
    public LeetcodeChallengeRecord setId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>leetcode_challenge.id</code>.
     */
    public Long getId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LeetcodeChallengeRecord
     */
    public LeetcodeChallengeRecord() {
        super(LeetcodeChallenge.LEETCODE_CHALLENGE);
    }

    /**
     * Create a detached, initialised LeetcodeChallengeRecord
     */
    public LeetcodeChallengeRecord(String frontendquestionid, String testcase, Long id) {
        super(LeetcodeChallenge.LEETCODE_CHALLENGE);

        setFrontendquestionid(frontendquestionid);
        setTestcase(testcase);
        setId(id);
        resetChangedOnNotNull();
    }
}
