/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables.records;


import com.wenjunhuang.codeepiphany.database.tables.LeetcodeSubmission;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LeetcodeSubmissionRecord extends UpdatableRecordImpl<LeetcodeSubmissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>leetcode_submission.id</code>.
     */
    public LeetcodeSubmissionRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>leetcode_submission.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>leetcode_submission.memory</code>.
     */
    public LeetcodeSubmissionRecord setMemory(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>leetcode_submission.memory</code>.
     */
    public Integer getMemory() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>leetcode_submission.totalCorrect</code>.
     */
    public LeetcodeSubmissionRecord setTotalcorrect(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>leetcode_submission.totalCorrect</code>.
     */
    public Integer getTotalcorrect() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>leetcode_submission.totalTestcases</code>.
     */
    public LeetcodeSubmissionRecord setTotaltestcases(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>leetcode_submission.totalTestcases</code>.
     */
    public Integer getTotaltestcases() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>leetcode_submission.statusMemory</code>.
     */
    public LeetcodeSubmissionRecord setStatusmemory(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>leetcode_submission.statusMemory</code>.
     */
    public String getStatusmemory() {
        return (String) get(4);
    }

    /**
     * Setter for <code>leetcode_submission.runtimePercentile</code>.
     */
    public LeetcodeSubmissionRecord setRuntimepercentile(Float value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>leetcode_submission.runtimePercentile</code>.
     */
    public Float getRuntimepercentile() {
        return (Float) get(5);
    }

    /**
     * Setter for <code>leetcode_submission.memoryPercentile</code>.
     */
    public LeetcodeSubmissionRecord setMemorypercentile(Float value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>leetcode_submission.memoryPercentile</code>.
     */
    public Float getMemorypercentile() {
        return (Float) get(6);
    }

    /**
     * Setter for <code>leetcode_submission.lastTestcase</code>.
     */
    public LeetcodeSubmissionRecord setLasttestcase(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>leetcode_submission.lastTestcase</code>.
     */
    public String getLasttestcase() {
        return (String) get(7);
    }

    /**
     * Setter for <code>leetcode_submission.inputFormatted</code>.
     */
    public LeetcodeSubmissionRecord setInputformatted(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>leetcode_submission.inputFormatted</code>.
     */
    public String getInputformatted() {
        return (String) get(8);
    }

    /**
     * Setter for <code>leetcode_submission.expectedOutput</code>.
     */
    public LeetcodeSubmissionRecord setExpectedoutput(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>leetcode_submission.expectedOutput</code>.
     */
    public String getExpectedoutput() {
        return (String) get(9);
    }

    /**
     * Setter for <code>leetcode_submission.codeOutput</code>.
     */
    public LeetcodeSubmissionRecord setCodeoutput(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>leetcode_submission.codeOutput</code>.
     */
    public String getCodeoutput() {
        return (String) get(10);
    }

    /**
     * Setter for <code>leetcode_submission.stdOutput</code>.
     */
    public LeetcodeSubmissionRecord setStdoutput(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>leetcode_submission.stdOutput</code>.
     */
    public String getStdoutput() {
        return (String) get(11);
    }

    /**
     * Setter for <code>leetcode_submission.statusRuntime</code>.
     */
    public LeetcodeSubmissionRecord setStatusruntime(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>leetcode_submission.statusRuntime</code>.
     */
    public String getStatusruntime() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LeetcodeSubmissionRecord
     */
    public LeetcodeSubmissionRecord() {
        super(LeetcodeSubmission.LEETCODE_SUBMISSION);
    }

    /**
     * Create a detached, initialised LeetcodeSubmissionRecord
     */
    public LeetcodeSubmissionRecord(Long id, Integer memory, Integer totalcorrect, Integer totaltestcases, String statusmemory, Float runtimepercentile, Float memorypercentile, String lasttestcase, String inputformatted, String expectedoutput, String codeoutput, String stdoutput, String statusruntime) {
        super(LeetcodeSubmission.LEETCODE_SUBMISSION);

        setId(id);
        setMemory(memory);
        setTotalcorrect(totalcorrect);
        setTotaltestcases(totaltestcases);
        setStatusmemory(statusmemory);
        setRuntimepercentile(runtimepercentile);
        setMemorypercentile(memorypercentile);
        setLasttestcase(lasttestcase);
        setInputformatted(inputformatted);
        setExpectedoutput(expectedoutput);
        setCodeoutput(codeoutput);
        setStdoutput(stdoutput);
        setStatusruntime(statusruntime);
        resetChangedOnNotNull();
    }
}
