/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables.records;


import com.wenjunhuang.codeepiphany.database.tables.SolutionSubmission;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SolutionSubmissionRecord extends UpdatableRecordImpl<SolutionSubmissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>solution_submission.id</code>.
     */
    public SolutionSubmissionRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>solution_submission.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>solution_submission.dojoSubmissionId</code>.
     */
    public SolutionSubmissionRecord setDojosubmissionid(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>solution_submission.dojoSubmissionId</code>.
     */
    public String getDojosubmissionid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>solution_submission.submitDateTime</code>.
     */
    public SolutionSubmissionRecord setSubmitdatetime(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>solution_submission.submitDateTime</code>.
     */
    public Integer getSubmitdatetime() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>solution_submission.localCode</code>.
     */
    public SolutionSubmissionRecord setLocalcode(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>solution_submission.localCode</code>.
     */
    public String getLocalcode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>solution_submission.submitCode</code>.
     */
    public SolutionSubmissionRecord setSubmitcode(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>solution_submission.submitCode</code>.
     */
    public String getSubmitcode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>solution_submission.state</code>.
     */
    public SolutionSubmissionRecord setState(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>solution_submission.state</code>.
     */
    public String getState() {
        return (String) get(5);
    }

    /**
     * Setter for <code>solution_submission.solutionId</code>.
     */
    public SolutionSubmissionRecord setSolutionid(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>solution_submission.solutionId</code>.
     */
    public Integer getSolutionid() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SolutionSubmissionRecord
     */
    public SolutionSubmissionRecord() {
        super(SolutionSubmission.SOLUTION_SUBMISSION);
    }

    /**
     * Create a detached, initialised SolutionSubmissionRecord
     */
    public SolutionSubmissionRecord(Integer id, String dojosubmissionid, Integer submitdatetime, String localcode, String submitcode, String state, Integer solutionid) {
        super(SolutionSubmission.SOLUTION_SUBMISSION);

        setId(id);
        setDojosubmissionid(dojosubmissionid);
        setSubmitdatetime(submitdatetime);
        setLocalcode(localcode);
        setSubmitcode(submitcode);
        setState(state);
        setSolutionid(solutionid);
        resetChangedOnNotNull();
    }
}
