/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables.records;


import com.wenjunhuang.codeepiphany.database.tables.Solution;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SolutionRecord extends UpdatableRecordImpl<SolutionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>solution.id</code>.
     */
    public SolutionRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>solution.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>solution.challengeId</code>.
     */
    public SolutionRecord setChallengeid(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>solution.challengeId</code>.
     */
    public Integer getChallengeid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>solution.challengeLanguageId</code>.
     */
    public SolutionRecord setChallengelanguageid(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>solution.challengeLanguageId</code>.
     */
    public Integer getChallengelanguageid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>solution.createDateTime</code>.
     */
    public SolutionRecord setCreatedatetime(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>solution.createDateTime</code>.
     */
    public Integer getCreatedatetime() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>solution.tags</code>.
     */
    public SolutionRecord setTags(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>solution.tags</code>.
     */
    public String getTags() {
        return (String) get(4);
    }

    /**
     * Setter for <code>solution.remark</code>.
     */
    public SolutionRecord setRemark(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>solution.remark</code>.
     */
    public String getRemark() {
        return (String) get(5);
    }

    /**
     * Setter for <code>solution.title</code>.
     */
    public SolutionRecord setTitle(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>solution.title</code>.
     */
    public String getTitle() {
        return (String) get(6);
    }

    /**
     * Setter for <code>solution.isDefault</code>.
     */
    public SolutionRecord setIsdefault(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>solution.isDefault</code>.
     */
    public Integer getIsdefault() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SolutionRecord
     */
    public SolutionRecord() {
        super(Solution.SOLUTION);
    }

    /**
     * Create a detached, initialised SolutionRecord
     */
    public SolutionRecord(Integer id, Integer challengeid, Integer challengelanguageid, Integer createdatetime, String tags, String remark, String title, Integer isdefault) {
        super(Solution.SOLUTION);

        setId(id);
        setChallengeid(challengeid);
        setChallengelanguageid(challengelanguageid);
        setCreatedatetime(createdatetime);
        setTags(tags);
        setRemark(remark);
        setTitle(title);
        setIsdefault(isdefault);
        resetChangedOnNotNull();
    }
}
