/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database.tables.records;


import com.wenjunhuang.codeepiphany.database.tables.SolutionSubmission;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SolutionSubmissionRecord extends UpdatableRecordImpl<SolutionSubmissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>solution_submission.id</code>.
     */
    public SolutionSubmissionRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>solution_submission.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>solution_submission.dojoSubmissionId</code>.
     */
    public SolutionSubmissionRecord setDojosubmissionid(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>solution_submission.dojoSubmissionId</code>.
     */
    public String getDojosubmissionid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>solution_submission.submitDateTime</code>.
     */
    public SolutionSubmissionRecord setSubmitdatetime(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>solution_submission.submitDateTime</code>.
     */
    public LocalDateTime getSubmitdatetime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>solution_submission.localCode</code>.
     */
    public SolutionSubmissionRecord setLocalcode(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>solution_submission.localCode</code>.
     */
    public String getLocalcode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>solution_submission.submitCode</code>.
     */
    public SolutionSubmissionRecord setSubmitcode(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>solution_submission.submitCode</code>.
     */
    public String getSubmitcode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>solution_submission.result</code>.
     */
    public SolutionSubmissionRecord setResult(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>solution_submission.result</code>.
     */
    public String getResult() {
        return (String) get(5);
    }

    /**
     * Setter for <code>solution_submission.solutionId</code>.
     */
    public SolutionSubmissionRecord setSolutionid(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>solution_submission.solutionId</code>.
     */
    public Integer getSolutionid() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>solution_submission.challengeLanguageId</code>.
     */
    public SolutionSubmissionRecord setChallengelanguageid(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>solution_submission.challengeLanguageId</code>.
     */
    public Integer getChallengelanguageid() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>solution_submission.score</code>.
     */
    public SolutionSubmissionRecord setScore(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>solution_submission.score</code>.
     */
    public String getScore() {
        return (String) get(8);
    }

    /**
     * Setter for <code>solution_submission.message</code>.
     */
    public SolutionSubmissionRecord setMessage(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>solution_submission.message</code>.
     */
    public String getMessage() {
        return (String) get(9);
    }

    /**
     * Setter for <code>solution_submission.resultDateTime</code>.
     */
    public SolutionSubmissionRecord setResultdatetime(LocalDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>solution_submission.resultDateTime</code>.
     */
    public LocalDateTime getResultdatetime() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SolutionSubmissionRecord
     */
    public SolutionSubmissionRecord() {
        super(SolutionSubmission.SOLUTION_SUBMISSION);
    }

    /**
     * Create a detached, initialised SolutionSubmissionRecord
     */
    public SolutionSubmissionRecord(Integer id, String dojosubmissionid, LocalDateTime submitdatetime, String localcode, String submitcode, String result, Integer solutionid, Integer challengelanguageid, String score, String message, LocalDateTime resultdatetime) {
        super(SolutionSubmission.SOLUTION_SUBMISSION);

        setId(id);
        setDojosubmissionid(dojosubmissionid);
        setSubmitdatetime(submitdatetime);
        setLocalcode(localcode);
        setSubmitcode(submitcode);
        setResult(result);
        setSolutionid(solutionid);
        setChallengelanguageid(challengelanguageid);
        setScore(score);
        setMessage(message);
        setResultdatetime(resultdatetime);
        resetChangedOnNotNull();
    }
}
