/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database;


import com.wenjunhuang.codeepiphany.database.tables.AtcoderContests;
import com.wenjunhuang.codeepiphany.database.tables.AtcoderContestsFts;
import com.wenjunhuang.codeepiphany.database.tables.AtcoderProblems;
import com.wenjunhuang.codeepiphany.database.tables.AtcoderProblemsFts;
import com.wenjunhuang.codeepiphany.database.tables.Challenge;
import com.wenjunhuang.codeepiphany.database.tables.ChallengeLanguage;
import com.wenjunhuang.codeepiphany.database.tables.CodeforcesChallenge;
import com.wenjunhuang.codeepiphany.database.tables.CodeforcesProblemsets;
import com.wenjunhuang.codeepiphany.database.tables.CodeforcesProblemsetsFts;
import com.wenjunhuang.codeepiphany.database.tables.HackerrankChallenge;
import com.wenjunhuang.codeepiphany.database.tables.HackerrankChallengeLanguage;
import com.wenjunhuang.codeepiphany.database.tables.HackerrankSubmissionCase;
import com.wenjunhuang.codeepiphany.database.tables.LeetcodeChallenge;
import com.wenjunhuang.codeepiphany.database.tables.LeetcodeSubmission;
import com.wenjunhuang.codeepiphany.database.tables.Solution;
import com.wenjunhuang.codeepiphany.database.tables.SolutionSubmission;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>atcoder_contests</code>.
     */
    public final AtcoderContests ATCODER_CONTESTS = AtcoderContests.ATCODER_CONTESTS;

    /**
     * The table <code>atcoder_contests_fts</code>.
     */
    public final AtcoderContestsFts ATCODER_CONTESTS_FTS = AtcoderContestsFts.ATCODER_CONTESTS_FTS;

    /**
     * The table <code>atcoder_problems</code>.
     */
    public final AtcoderProblems ATCODER_PROBLEMS = AtcoderProblems.ATCODER_PROBLEMS;

    /**
     * The table <code>atcoder_problems_fts</code>.
     */
    public final AtcoderProblemsFts ATCODER_PROBLEMS_FTS = AtcoderProblemsFts.ATCODER_PROBLEMS_FTS;

    /**
     * The table <code>challenge</code>.
     */
    public final Challenge CHALLENGE = Challenge.CHALLENGE;

    /**
     * The table <code>challenge_language</code>.
     */
    public final ChallengeLanguage CHALLENGE_LANGUAGE = ChallengeLanguage.CHALLENGE_LANGUAGE;

    /**
     * The table <code>codeforces_challenge</code>.
     */
    public final CodeforcesChallenge CODEFORCES_CHALLENGE = CodeforcesChallenge.CODEFORCES_CHALLENGE;

    /**
     * The table <code>codeforces_problemsets</code>.
     */
    public final CodeforcesProblemsets CODEFORCES_PROBLEMSETS = CodeforcesProblemsets.CODEFORCES_PROBLEMSETS;

    /**
     * The table <code>codeforces_problemsets_fts</code>.
     */
    public final CodeforcesProblemsetsFts CODEFORCES_PROBLEMSETS_FTS = CodeforcesProblemsetsFts.CODEFORCES_PROBLEMSETS_FTS;

    /**
     * The table <code>hackerrank_challenge</code>.
     */
    public final HackerrankChallenge HACKERRANK_CHALLENGE = HackerrankChallenge.HACKERRANK_CHALLENGE;

    /**
     * The table <code>hackerrank_challenge_language</code>.
     */
    public final HackerrankChallengeLanguage HACKERRANK_CHALLENGE_LANGUAGE = HackerrankChallengeLanguage.HACKERRANK_CHALLENGE_LANGUAGE;

    /**
     * The table <code>hackerrank_submission_case</code>.
     */
    public final HackerrankSubmissionCase HACKERRANK_SUBMISSION_CASE = HackerrankSubmissionCase.HACKERRANK_SUBMISSION_CASE;

    /**
     * The table <code>leetcode_challenge</code>.
     */
    public final LeetcodeChallenge LEETCODE_CHALLENGE = LeetcodeChallenge.LEETCODE_CHALLENGE;

    /**
     * The table <code>leetcode_submission</code>.
     */
    public final LeetcodeSubmission LEETCODE_SUBMISSION = LeetcodeSubmission.LEETCODE_SUBMISSION;

    /**
     * The table <code>solution</code>.
     */
    public final Solution SOLUTION = Solution.SOLUTION;

    /**
     * The table <code>solution_submission</code>.
     */
    public final SolutionSubmission SOLUTION_SUBMISSION = SolutionSubmission.SOLUTION_SUBMISSION;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AtcoderContests.ATCODER_CONTESTS,
            AtcoderContestsFts.ATCODER_CONTESTS_FTS,
            AtcoderProblems.ATCODER_PROBLEMS,
            AtcoderProblemsFts.ATCODER_PROBLEMS_FTS,
            Challenge.CHALLENGE,
            ChallengeLanguage.CHALLENGE_LANGUAGE,
            CodeforcesChallenge.CODEFORCES_CHALLENGE,
            CodeforcesProblemsets.CODEFORCES_PROBLEMSETS,
            CodeforcesProblemsetsFts.CODEFORCES_PROBLEMSETS_FTS,
            HackerrankChallenge.HACKERRANK_CHALLENGE,
            HackerrankChallengeLanguage.HACKERRANK_CHALLENGE_LANGUAGE,
            HackerrankSubmissionCase.HACKERRANK_SUBMISSION_CASE,
            LeetcodeChallenge.LEETCODE_CHALLENGE,
            LeetcodeSubmission.LEETCODE_SUBMISSION,
            Solution.SOLUTION,
            SolutionSubmission.SOLUTION_SUBMISSION
        );
    }
}
