/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database;


import com.wenjunhuang.codeepiphany.database.tables.Challenge;
import com.wenjunhuang.codeepiphany.database.tables.ChallengeLanguage;
import com.wenjunhuang.codeepiphany.database.tables.HackerrankChallenge;
import com.wenjunhuang.codeepiphany.database.tables.HackerrankChallengeLanguage;
import com.wenjunhuang.codeepiphany.database.tables.HackerrankSubmissionCase;
import com.wenjunhuang.codeepiphany.database.tables.Solution;
import com.wenjunhuang.codeepiphany.database.tables.SolutionSubmission;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>challenge</code>.
     */
    public final Challenge CHALLENGE = Challenge.CHALLENGE;

    /**
     * The table <code>challenge_language</code>.
     */
    public final ChallengeLanguage CHALLENGE_LANGUAGE = ChallengeLanguage.CHALLENGE_LANGUAGE;

    /**
     * The table <code>hackerrank_challenge</code>.
     */
    public final HackerrankChallenge HACKERRANK_CHALLENGE = HackerrankChallenge.HACKERRANK_CHALLENGE;

    /**
     * The table <code>hackerrank_challenge_language</code>.
     */
    public final HackerrankChallengeLanguage HACKERRANK_CHALLENGE_LANGUAGE = HackerrankChallengeLanguage.HACKERRANK_CHALLENGE_LANGUAGE;

    /**
     * The table <code>hackerrank_submission_case</code>.
     */
    public final HackerrankSubmissionCase HACKERRANK_SUBMISSION_CASE = HackerrankSubmissionCase.HACKERRANK_SUBMISSION_CASE;

    /**
     * The table <code>solution</code>.
     */
    public final Solution SOLUTION = Solution.SOLUTION;

    /**
     * The table <code>solution_submission</code>.
     */
    public final SolutionSubmission SOLUTION_SUBMISSION = SolutionSubmission.SOLUTION_SUBMISSION;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Challenge.CHALLENGE,
            ChallengeLanguage.CHALLENGE_LANGUAGE,
            HackerrankChallenge.HACKERRANK_CHALLENGE,
            HackerrankChallengeLanguage.HACKERRANK_CHALLENGE_LANGUAGE,
            HackerrankSubmissionCase.HACKERRANK_SUBMISSION_CASE,
            Solution.SOLUTION,
            SolutionSubmission.SOLUTION_SUBMISSION
        );
    }
}
