/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database;


import com.wenjunhuang.codeepiphany.database.tables.Challenge;
import com.wenjunhuang.codeepiphany.database.tables.CodeforcesProblemsets;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CHALLENGE_DOJOID_DOJO_UINDEX = Internal.createIndex(DSL.name("challenge_dojoId_dojo_uindex"), Challenge.CHALLENGE, new OrderField[] { Challenge.CHALLENGE.DOJOID, Challenge.CHALLENGE.DOJO }, true);
    public static final Index CODEFORCES_PROBLEMSETS_CONTESTID_INDEX_INDEX = Internal.createIndex(DSL.name("codeforces_problemsets_contestId_index_index"), CodeforcesProblemsets.CODEFORCES_PROBLEMSETS, new OrderField[] { CodeforcesProblemsets.CODEFORCES_PROBLEMSETS.CONTESTID, CodeforcesProblemsets.CODEFORCES_PROBLEMSETS.INDEX }, false);
}
