/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database;


import com.wenjunhuang.codeepiphany.database.tables.Challenge;
import com.wenjunhuang.codeepiphany.database.tables.ChallengeLanguage;
import com.wenjunhuang.codeepiphany.database.tables.Solution;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CHALLENGE_DOJOID_DOJO_UINDEX = Internal.createIndex(DSL.name("challenge_dojoId_dojo_uindex"), Challenge.CHALLENGE, new OrderField[] { Challenge.CHALLENGE.DOJOID, Challenge.CHALLENGE.DOJO }, true);
    public static final Index CHALLENGE_LANGUAGE_CHALLENGEID_LANGUAGE_UINDEX = Internal.createIndex(DSL.name("challenge_language_challengeId_language_uindex"), ChallengeLanguage.CHALLENGE_LANGUAGE, new OrderField[] { ChallengeLanguage.CHALLENGE_LANGUAGE.CHALLENGEID, ChallengeLanguage.CHALLENGE_LANGUAGE.LANGUAGE }, true);
    public static final Index SOLUTION_CHALLENGELANGUAGEID_TITLE_UINDEX = Internal.createIndex(DSL.name("solution_challengeLanguageId_title_uindex"), Solution.SOLUTION, new OrderField[] { Solution.SOLUTION.CHALLENGELANGUAGEID, Solution.SOLUTION.TITLE }, true);
}
