/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database;


import com.wenjunhuang.codeepiphany.database.tables.Challenge;
import com.wenjunhuang.codeepiphany.database.tables.HackerrankChallenge;
import com.wenjunhuang.codeepiphany.database.tables.records.ChallengeRecord;
import com.wenjunhuang.codeepiphany.database.tables.records.HackerrankChallengeRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChallengeRecord> CHALLENGE__PK_CHALLENGE = Internal.createUniqueKey(Challenge.CHALLENGE, DSL.name("pk_challenge"), new TableField[] { Challenge.CHALLENGE.ID }, true);
    public static final UniqueKey<HackerrankChallengeRecord> HACKERRANK_CHALLENGE__PK_HACKERRANK_CHALLENGE = Internal.createUniqueKey(HackerrankChallenge.HACKERRANK_CHALLENGE, DSL.name("pk_hackerrank_challenge"), new TableField[] { HackerrankChallenge.HACKERRANK_CHALLENGE.CHALLENGEID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<HackerrankChallengeRecord, ChallengeRecord> HACKERRANK_CHALLENGE__FK_HACKERRANK_CHALLENGE_PK_CHALLENGE = Internal.createForeignKey(HackerrankChallenge.HACKERRANK_CHALLENGE, DSL.name("fk_hackerrank_challenge_pk_challenge"), new TableField[] { HackerrankChallenge.HACKERRANK_CHALLENGE.CHALLENGEID }, Keys.CHALLENGE__PK_CHALLENGE, new TableField[] { Challenge.CHALLENGE.ID }, true);
}
