/*
 * This file is generated by jOOQ.
 */
package com.wenjunhuang.codeepiphany.database;


import com.wenjunhuang.codeepiphany.database.tables.Challenge;
import com.wenjunhuang.codeepiphany.database.tables.ChallengeLanguage;
import com.wenjunhuang.codeepiphany.database.tables.CodeforcesChallenge;
import com.wenjunhuang.codeepiphany.database.tables.CodeforcesProblemsets;
import com.wenjunhuang.codeepiphany.database.tables.CodeforcesProblemsetsFts;
import com.wenjunhuang.codeepiphany.database.tables.HackerrankChallenge;
import com.wenjunhuang.codeepiphany.database.tables.HackerrankChallengeLanguage;
import com.wenjunhuang.codeepiphany.database.tables.HackerrankSubmissionCase;
import com.wenjunhuang.codeepiphany.database.tables.LeetcodeChallenge;
import com.wenjunhuang.codeepiphany.database.tables.LeetcodeSubmission;
import com.wenjunhuang.codeepiphany.database.tables.Solution;
import com.wenjunhuang.codeepiphany.database.tables.SolutionSubmission;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>challenge</code>.
     */
    public static final Challenge CHALLENGE = Challenge.CHALLENGE;

    /**
     * The table <code>challenge_language</code>.
     */
    public static final ChallengeLanguage CHALLENGE_LANGUAGE = ChallengeLanguage.CHALLENGE_LANGUAGE;

    /**
     * The table <code>codeforces_challenge</code>.
     */
    public static final CodeforcesChallenge CODEFORCES_CHALLENGE = CodeforcesChallenge.CODEFORCES_CHALLENGE;

    /**
     * The table <code>codeforces_problemsets</code>.
     */
    public static final CodeforcesProblemsets CODEFORCES_PROBLEMSETS = CodeforcesProblemsets.CODEFORCES_PROBLEMSETS;

    /**
     * The table <code>codeforces_problemsets_fts</code>.
     */
    public static final CodeforcesProblemsetsFts CODEFORCES_PROBLEMSETS_FTS = CodeforcesProblemsetsFts.CODEFORCES_PROBLEMSETS_FTS;

    /**
     * The table <code>hackerrank_challenge</code>.
     */
    public static final HackerrankChallenge HACKERRANK_CHALLENGE = HackerrankChallenge.HACKERRANK_CHALLENGE;

    /**
     * The table <code>hackerrank_challenge_language</code>.
     */
    public static final HackerrankChallengeLanguage HACKERRANK_CHALLENGE_LANGUAGE = HackerrankChallengeLanguage.HACKERRANK_CHALLENGE_LANGUAGE;

    /**
     * The table <code>hackerrank_submission_case</code>.
     */
    public static final HackerrankSubmissionCase HACKERRANK_SUBMISSION_CASE = HackerrankSubmissionCase.HACKERRANK_SUBMISSION_CASE;

    /**
     * The table <code>leetcode_challenge</code>.
     */
    public static final LeetcodeChallenge LEETCODE_CHALLENGE = LeetcodeChallenge.LEETCODE_CHALLENGE;

    /**
     * The table <code>leetcode_submission</code>.
     */
    public static final LeetcodeSubmission LEETCODE_SUBMISSION = LeetcodeSubmission.LEETCODE_SUBMISSION;

    /**
     * The table <code>solution</code>.
     */
    public static final Solution SOLUTION = Solution.SOLUTION;

    /**
     * The table <code>solution_submission</code>.
     */
    public static final SolutionSubmission SOLUTION_SUBMISSION = SolutionSubmission.SOLUTION_SUBMISSION;
}
