query questionData($titleSlug: String!) {
    question(titleSlug: $titleSlug) {
        questionId
        frontendQuestionId: questionFrontendId
        title
        titleSlug
        content
        translatedTitle
        translatedContent
        isPaidOnly
        difficulty
        likes
        dislikes
        isLiked
        similarQuestions
        exampleTestcaseList
        testCase: sampleTestCase
        topicTags {
            name
            slug
            translatedName
        }
        codeSnippets {
            lang
            langSlug
            code
        }
        hints
        solution {
            id
            canSeeDetail
        }
        status
        metaData
        judgerAvailable
        judgeType
        mysqlSchemas
        libraryUrl
    }
}
